"""Stamp out the turret-duel probe pairs into bots/probes/.

Every probe is a parameterisation of one template.  The CORE is always the
reporter (it cannot die here and it has the lowest entity id, so it runs first
every round); the builder and the turret publish everything through the 16
team-wide store slots, which carry a one-round write lag.

Arena: maps/lab/firstshot.map26 (built by maps/lab/mkduel.py).
"""

import pathlib
import shutil

ROOT = pathlib.Path(r"c:/Users/edlun/Desktop/lucky shots/Hackathons/florent-code-league")
PROBES = ROOT / "bots" / "probes"

TEMPLATE = '''"""AUTO-GENERATED by scratchpad/gen_duel.py -- turret first-strike duel, side {side}.

maps/lab/firstshot.map26.  Core spawns ONE builder on round {spawn_round}; the builder
walks to {bpos}, builds a {turret} at {tpos} facing {facing} on round
{build_round}, then steps to {obs}.  Fire mode "{mode}":
  duel -- the turret only ever fires at the enemy turret tile {etpos}
  free -- the turret fires at any enemy entity inside its attackable tiles

The CORE reports (reporter={report}); everything else is relayed through store
slots, so the report survives the builder and the turret being killed.
"""

from fcode import Controller, Direction, EntityType, Position

SIDE = "{side}"
SPAWN = Position{spawn}
BPOS = Position{bpos}
TPOS = Position{tpos}
OBS = Position{obs}
ETPOS = Position{etpos}
FACING = Direction.{facing}
WALK = [Direction.{walk}, Direction.{walk}]
SPAWN_ROUND = {spawn_round}
BUILD_ROUND = {build_round}
RESIGN_ROUND = {resign_round}
LOG_FROM = {log_from}
REPORT = {report}
TURRET = "{turret}"
MODE = "{mode}"

# ---- store slots (team-wide, one-round write lag).  All values are +1 so that
# 0 means "never written".
T_SHOTS, T_LASTFIRE, T_FOEHP, T_OWNHP, T_ID, T_SATK, T_FIRST = 0, 1, 2, 3, 4, 5, 6
B_BEAT, B_ID, B_TID, B_BROUND, B_EID, B_EHP, B_OHP, B_FIRST = 7, 8, 9, 10, 11, 12, 13, 14


def _w(ct, slot, val):
    try:
        ct.write_store(slot, max(0, min(4294967295, int(val))))
    except Exception:
        pass


class Player:
    def __init__(self):
        self.err = []
        self.spawned = None
        self.log = []
        self.last = None
        self.dead_own = "-"
        self.dead_foe = "-"
        self.step = 0
        self.shots = 0
        self.lastfire = -1
        self.first = None
        self.tid = None

    def run(self, ct: Controller) -> None:
        try:
            self._run(ct)
        except Exception as exc:
            if len(self.err) < 6:
                self.err.append("%s:%s" % (type(exc).__name__, str(exc)[:60]))

    def _run(self, ct):
        et = ct.get_entity_type()
        if et == EntityType.CORE:
            self._core(ct)
        elif et == EntityType.BUILDER_BOT:
            self._builder(ct)
        elif et in (EntityType.SENTINEL, EntityType.GUNNER):
            self._turret(ct)

    # ------------------------------------------------------------------ core
    def _core(self, ct):
        r = ct.get_current_round()
        if self.first is None:
            self.first = r
        if REPORT:
            self._sample(ct, r)
        if self.spawned is None and r >= SPAWN_ROUND:
            if ct.can_spawn(SPAWN):
                self.spawned = ct.spawn_builder(SPAWN)
                return
        try:
            # keep a 200 Ti reserve so the builder can always afford the turret
            if (ct.get_global_ammo() < 300 and ct.get_global_resources() > 200
                    and ct.can_convert_ammo(50)):
                ct.convert_ammo(50)
        except Exception:
            pass

    def _sample(self, ct, r):
        try:
            v = tuple(ct.read_store(i) for i in range(15))
        except Exception:
            return
        # builder's start-of-round view of the two turret tiles, lagged 1 round
        hp = (v[B_OHP], v[B_EHP])
        if hp != self.last and r >= LOG_FROM:
            f = lambda x: (x - 1) if x else "x"          # noqa: E731
            self.log.append("%d:%s/%s" % (r - 1, f(hp[0]), f(hp[1])))
            if hp[0] == 0 and self.last and self.last[0]:
                self.dead_own = r - 1
            if hp[1] == 0 and self.last and self.last[1]:
                self.dead_foe = r - 1
            self.last = hp
        elif self.last is None:
            self.last = hp
        if r >= RESIGN_ROUND:
            ct.resign(self._msg(ct, v))

    def _msg(self, ct, v):
        d = lambda i: v[i] - 1 if v[i] else "x"          # noqa: E731
        try:
            ammo = ct.get_global_ammo()
        except Exception:
            ammo = -1
        head = ("%s|%s|%s|bR%d|bid%s|tid%s|br%s|tf%s|eid%s|satk%s|sh%s|lf%s|"
                "dOWN%s|dFOE%s|am%s|E%s|HP "
                % (SIDE, TURRET[0], MODE, BUILD_ROUND, d(B_ID), d(B_TID),
                   d(B_BROUND), d(T_FIRST), d(B_EID), d(T_SATK),
                   d(T_SHOTS), d(T_LASTFIRE), self.dead_own, self.dead_foe,
                   ammo, ";".join(self.err[:2])))
        room = 490 - len(head)
        body = " ".join(self.log)
        if len(body) > room:
            body = body[:room]
        return head + body

    # --------------------------------------------------------------- builder
    def _builder(self, ct):
        r = ct.get_current_round()
        _w(ct, B_BEAT, r + 1)
        _w(ct, B_ID, ct.get_id() + 1)
        if self.first is None:
            self.first = r
            _w(ct, B_FIRST, r + 1)

        # observe both turret tiles at OUR turn (builder id < turret ids, so this
        # is the state at the START of the round)
        for tile, slot in ((TPOS, B_OHP), (ETPOS, B_EHP)):
            try:
                b = ct.get_tile_building_id(tile)
                _w(ct, slot, (ct.get_hp(b) + 1) if b is not None else 0)
                if tile == ETPOS and b is not None:
                    _w(ct, B_EID, b + 1)
            except Exception:
                pass

        if self.step < len(WALK):
            d = WALK[self.step]
            if ct.can_move(d):
                ct.move(d)
                self.step += 1
            return

        if self.step == len(WALK):
            if r < BUILD_ROUND:
                return
            try:
                if TURRET == "sentinel":
                    if not ct.can_build_sentinel(TPOS, FACING):
                        return
                    self.tid = ct.build_sentinel(TPOS, FACING)
                else:
                    if not ct.can_build_gunner(TPOS, FACING):
                        return
                    self.tid = ct.build_gunner(TPOS, FACING)
            except Exception as exc:
                self.err.append("B:%s" % str(exc)[:40])
                return
            _w(ct, B_TID, self.tid + 1)
            _w(ct, B_BROUND, r + 1)
            self.step += 1
            return

        if self.step == len(WALK) + 1:
            if ct.can_move(Direction.NORTH):
                ct.move(Direction.NORTH)
            self.step += 1
            return

    # ---------------------------------------------------------------- turret
    def _turret(self, ct):
        r = ct.get_current_round()
        if self.first is None:
            self.first = r
            _w(ct, T_FIRST, r + 1)
            _w(ct, T_ID, ct.get_id() + 1)
            try:
                _w(ct, T_SATK, len(ct.get_attackable_tiles()) + 1)
            except Exception:
                pass

        foehp = None
        try:
            b = ct.get_tile_building_id(ETPOS)
            if b is not None:
                foehp = ct.get_hp(b)
        except Exception:
            pass
        _w(ct, T_FOEHP, (foehp + 1) if foehp is not None else 0)
        try:
            _w(ct, T_OWNHP, ct.get_hp() + 1)
        except Exception:
            pass

        target = None
        try:
            if MODE == "void":
                # fire at the enemy turret TILE whenever the engine allows it,
                # occupied or not -- this is what documents empty-tile firing
                if ct.can_fire(ETPOS):
                    target = ETPOS
            elif MODE == "duel":
                # strict duel: only ever shoot a real enemy turret
                b = ct.get_tile_building_id(ETPOS)
                if b is not None and ct.can_fire(ETPOS):
                    target = ETPOS
            else:  # free
                me = ct.get_team()
                for p in ct.get_attackable_tiles():
                    try:
                        hit = ct.get_tile_building_id(p)
                        if hit is None:
                            hit = ct.get_tile_builder_bot_id(p)
                        if (hit is not None and ct.get_team(hit) != me
                                and ct.can_fire(p)):
                            target = p
                            break
                    except Exception:
                        pass
        except Exception:
            pass
        if target is not None:
            try:
                ct.fire(target)
                self.shots += 1
                self.lastfire = r
            except Exception as exc:
                if len(self.err) < 6:
                    self.err.append("F:%s" % str(exc)[:40])
        _w(ct, T_SHOTS, self.shots + 1)
        _w(ct, T_LASTFIRE, self.lastfire + 1)
'''

GEOM = {
    "A": dict(spawn=(3, 4), bpos=(5, 4), tpos=(6, 4), obs=(5, 3), etpos=(9, 4),
              facing="EAST", walk="EAST"),
    "B": dict(spawn=(12, 4), bpos=(10, 4), tpos=(9, 4), obs=(10, 3), etpos=(6, 4),
              facing="WEST", walk="WEST"),
}


def make(name, side, turret, spawn_round, build_round, report,
         mode="duel", resign_round=60, log_from=0):
    g = GEOM[side]
    src = TEMPLATE.format(
        side=side, turret=turret, spawn=g["spawn"], bpos=g["bpos"], tpos=g["tpos"],
        obs=g["obs"], etpos=g["etpos"], facing=g["facing"], walk=g["walk"],
        spawn_round=spawn_round, build_round=build_round, log_from=log_from,
        resign_round=resign_round, report=report, mode=mode,
    )
    d = PROBES / name
    if (d / "__pycache__").exists():
        shutil.rmtree(d / "__pycache__")
    d.mkdir(parents=True, exist_ok=True)
    (d / "main.py").write_text(src, encoding="utf-8")
    return name


PAIRS = []


def pair(tag, turret, spawn_a, build_a, spawn_b, build_b, mode="duel", resign=60):
    lf = min(build_a, build_b) - 2
    a = make("du_%s_a" % tag, "A", turret, spawn_a, build_a, True, mode, resign, lf)
    b = make("du_%s_b" % tag, "B", turret, spawn_b, build_b, False, mode, resign, lf)
    PAIRS.append((tag, a, b))


if __name__ == "__main__":
    for turret in ("sentinel", "gunner"):
        k = turret[0]
        # interleave test: identical build round, spawn order decides which
        # BUILDER holds the lower id and therefore which TURRET holds it.
        pair("%s_af" % k, turret, 1, 20, 2, 20)   # A's builder id 3 -> A turret id 5
        pair("%s_bf" % k, turret, 2, 20, 1, 20)   # B's builder id 3 -> B turret id 5
        # head start: B builds h rounds EARLIER (A's builder still holds id 3)
        for h in (1, 2, 3, 4, 6, 8):
            pair("%s_h%d" % (k, h), turret, 1, 20, 2, 20 - h)
        # mirror: A builds h rounds earlier
        for h in (1, 3, 4):
            pair("%s_m%d" % (k, h), turret, 1, 20 - h, 2, 20)
        # free-fire: B arrives early and may shoot A's incoming builder
        for h in (4, 5, 6, 7, 8, 12):
            pair("%s_f%d" % (k, h), turret, 1, 20, 2, 20 - h, "free")
        # mirror of the free-fire denial: A is the early side
        for h in (6, 8):
            pair("%s_fm%d" % (k, h), turret, 1, 20 - h, 2, 20, "free")
        # void mode: the early turret keeps firing at the empty enemy turret
        # tile, which is how empty-tile firing was first noticed
        pair("%s_v4" % k, turret, 1, 20, 2, 16, "void")
        pair("%s_v0" % k, turret, 1, 20, 2, 20, "void")
    print(len(PAIRS), "pairs written")
    for t, a, b in PAIRS:
        print(t, a, b)
