"""Offline map atlas for the Florent Code League 2026 15-map pool.

GENERATED by ``tools/build_atlas.py`` from ``maps/*.map26`` -- DO NOT EDIT BY HAND.

Pure stdlib (no imports at all), safe inside the bot sandbox and cheap to import in every
per-unit sub-interpreter.

Public interface
----------------
``identify(width, height, core_pos, team)``
    Return the record dict for this game, or ``None`` when the fingerprint is unrecognised.
    Never raises. ``core_pos`` is OUR Core's reported ``Position`` (any (x, y) sequence);
    ``team`` is ``'a'`` or ``'b'`` (a ``Team`` enum or ``'Team.A'`` also works).

``mirror(record, pos)``
    Map a position to its counterpart in the enemy half, using that map's symmetry.

``by_name(name, team)`` / ``MAP_NAMES``
    Offline lookups for tools and tests.

Record keys
-----------
``name``            str
``width``           int
``height``          int
``walls``           frozenset of (x, y) -- every WALL tile on the map
``ore``             tuple of (x, y)     -- every ORE_TITANIUM tile, row-major sorted
``own_core``        (x, y)              -- OUR Core anchor, resolved for the calling team
``enemy_core``      (x, y)              -- THEIR Core anchor
``own_core_tiles``  tuple of 4 (x, y)   -- the 2x2 footprint our Core occupies
``enemy_core_tiles``tuple of 4 (x, y)
``symmetry``        str -- one of 'rot180', 'mirror_x', 'mirror_y', 'diag'

Symmetry naming: ``mirror_x`` flips the x coordinate (reflection across the vertical centre
line), ``mirror_y`` flips y, ``rot180`` flips both, ``diag`` is the anti-diagonal reflection
``(x, y) -> (h-1-y, w-1-x)`` (square maps only). Each map's symmetry was determined
empirically -- the transform provably maps walls onto walls, ore onto ore and Core A's
footprint onto Core B's.

Engine facts this rests on (all probe-verified on 15/15 maps, both teams):
a Core's ``get_position()`` is the map-file anchor and is the TOP-LEFT of its 2x2 footprint;
``get_map_width()/get_map_height()`` match the file; owner 1 == Team A, owner 2 == Team B.
"""

# name, w, h, walls, ore, coreA anchor, coreB anchor, symmetry
_DATA = (
    ("atoll", 18, 18,
     (
        (6,6),(7,6),(8,6),(9,6),(10,6),(11,6),(6,7),(11,7),(6,8),(11,9),(6,10),(11,10),(6,11),
        (7,11),(8,11),(9,11),(10,11),(11,11),
      ),
     (
        (16,0),(12,1),(8,8),(9,8),(8,9),(9,9),(5,16),(1,17),
      ),
     (2,14), (14,2), "rot180"),
    ("aurora", 26, 26,
     (
        (0,6),(1,6),(2,6),(3,6),(4,6),(5,6),(6,6),(7,6),(8,6),(9,6),(10,6),(11,6),(12,6),(13,6),
        (14,6),(15,6),(8,12),(9,12),(10,12),(11,12),(12,12),(13,12),(14,12),(15,12),(16,12),
        (17,12),(18,12),(19,12),(20,12),(21,12),(22,12),(23,12),(2,13),(3,13),(4,13),(5,13),
        (6,13),(7,13),(8,13),(9,13),(10,13),(11,13),(12,13),(13,13),(14,13),(15,13),(16,13),
        (17,13),(10,19),(11,19),(12,19),(13,19),(14,19),(15,19),(16,19),(17,19),(18,19),(19,19),
        (20,19),(21,19),(22,19),(23,19),(24,19),(25,19),
      ),
     (
        (13,0),(24,0),(18,1),(4,9),(12,9),(20,9),(1,10),(24,15),(5,16),(13,16),(21,16),(7,24),
        (1,25),(12,25),
      ),
     (3,22), (21,2), "rot180"),
    ("crossfire", 16, 16,
     (
        (7,0),(7,1),(7,2),(7,3),(7,4),(7,5),(0,7),(1,7),(2,7),(3,7),(4,7),(5,7),(10,8),(11,8),
        (12,8),(13,8),(14,8),(15,8),(8,10),(8,11),(8,12),(8,13),(8,14),(8,15),
      ),
     (
        (14,1),(2,2),(10,2),(4,3),(7,7),(8,8),(11,12),(5,13),(13,13),(1,14),
      ),
     (2,11), (12,3), "rot180"),
    ("duel", 12, 12,
     (
        (6,5),(5,6),
      ),
     (
        (10,0),(7,1),(5,5),(6,6),(4,10),(1,11),
      ),
     (1,8), (9,2), "rot180"),
    ("fjord", 20, 20,
     (
        (8,4),(9,5),(10,6),(11,7),(4,8),(12,8),(0,9),(1,9),(5,9),(13,9),(6,10),(14,10),(18,10),
        (19,10),(7,11),(15,11),(8,12),(9,13),(10,14),(11,15),
      ),
     (
        (17,1),(18,1),(4,2),(14,2),(8,8),(9,9),(10,10),(11,11),(5,17),(15,17),(1,18),(2,18),
      ),
     (2,15), (16,3), "rot180"),
    ("hive", 25, 25,
     (
        (1,1),(5,1),(9,1),(13,1),(17,1),(21,1),(1,5),(5,5),(9,5),(13,5),(17,5),(1,9),(5,9),
        (9,9),(13,9),(17,9),(21,9),(3,15),(7,15),(11,15),(15,15),(19,15),(23,15),(7,19),(11,19),
        (15,19),(19,19),(23,19),(3,23),(7,23),(11,23),(15,23),(19,23),(23,23),
      ),
     (
        (11,3),(7,7),(15,7),(23,7),(11,11),(19,11),(5,13),(13,13),(1,17),(9,17),(17,17),(13,21),
      ),
     (2,20), (21,3), "rot180"),
    ("longship", 28, 20,
     (
        (6,3),(7,3),(8,3),(9,3),(10,3),(11,3),(12,3),(13,3),(14,3),(15,3),(16,3),(17,3),(18,3),
        (19,3),(20,3),(21,3),(4,5),(23,5),(3,6),(24,6),(3,13),(24,13),(4,14),(23,14),(6,16),
        (7,16),(8,16),(9,16),(10,16),(11,16),(12,16),(13,16),(14,16),(15,16),(16,16),(17,16),
        (18,16),(19,16),(20,16),(21,16),
      ),
     (
        (6,1),(21,1),(1,5),(26,5),(10,9),(13,9),(14,9),(17,9),(9,10),(12,10),(15,10),(18,10),
        (1,12),(26,12),(6,18),(21,18),
      ),
     (2,8), (24,8), "mirror_x"),
    ("pinch", 14, 18,
     (
        (0,8),(1,8),(2,8),(3,8),(4,8),(5,8),(8,8),(9,8),(10,8),(11,8),(12,8),(13,8),(0,9),(1,9),
        (2,9),(3,9),(4,9),(5,9),(8,9),(9,9),(10,9),(11,9),(12,9),(13,9),
      ),
     (
        (6,1),(11,2),(6,6),(7,6),(12,7),(12,10),(6,11),(7,11),(11,15),(6,16),
      ),
     (2,2), (2,14), "mirror_y"),
    ("quarry", 24, 24,
     (
        (11,5),(12,5),(5,11),(18,11),(5,12),(18,12),(11,18),(12,18),
      ),
     (
        (6,6),(7,6),(17,6),(18,6),(6,7),(7,7),(16,7),(17,7),(18,7),(11,11),(12,11),(11,12),
        (12,12),(5,16),(6,16),(7,16),(16,16),(17,16),(5,17),(6,17),(16,17),(17,17),
      ),
     (2,2), (20,20), "rot180"),
    ("runestone", 24, 24,
     (
        (11,8),(12,8),(11,9),(12,9),(11,10),(12,10),(11,11),(12,11),(11,12),(12,12),(11,13),
        (12,13),(11,14),(12,14),(11,15),(12,15),
      ),
     (
        (5,2),(18,2),(10,6),(13,6),(1,7),(22,7),(9,9),(14,9),(9,14),(14,14),(1,16),(22,16),
        (10,17),(13,17),(5,21),(18,21),
      ),
     (2,11), (20,11), "rot180"),
    ("skerry", 22, 22,
     (
        (9,4),(10,4),(9,5),(10,5),(15,6),(16,6),(15,7),(16,7),(14,8),(15,8),(14,9),(15,9),
        (6,12),(7,12),(6,13),(7,13),(5,14),(6,14),(5,15),(6,15),(11,16),(12,16),(11,17),(12,17),
      ),
     (
        (18,1),(20,1),(8,5),(17,7),(13,9),(10,10),(11,11),(8,12),(4,14),(13,16),(1,20),(3,20),
      ),
     (2,17), (18,3), "rot180"),
    ("sprint", 10, 10,
     (),
     (
        (6,1),(8,3),(4,4),(5,5),(1,6),(3,8),
      ),
     (1,1), (7,7), "rot180"),
    ("strait", 20, 26,
     (
        (0,11),(1,11),(2,11),(3,11),(6,11),(7,11),(8,11),(9,11),(10,11),(11,11),(12,11),(13,11),
        (16,11),(17,11),(18,11),(19,11),(0,12),(1,12),(2,12),(3,12),(6,12),(7,12),(8,12),(9,12),
        (10,12),(11,12),(12,12),(13,12),(16,12),(17,12),(18,12),(19,12),(0,13),(1,13),(2,13),
        (3,13),(6,13),(7,13),(8,13),(9,13),(10,13),(11,13),(12,13),(13,13),(16,13),(17,13),
        (18,13),(19,13),(0,14),(1,14),(2,14),(3,14),(6,14),(7,14),(8,14),(9,14),(10,14),(11,14),
        (12,14),(13,14),(16,14),(17,14),(18,14),(19,14),
      ),
     (
        (6,1),(17,4),(1,6),(4,9),(15,9),(9,10),(9,15),(4,16),(15,16),(1,19),(17,21),(6,24),
      ),
     (2,2), (2,22), "mirror_y"),
    ("twins", 21, 21,
     (
        (0,10),(1,10),(2,10),(5,10),(6,10),(7,10),(8,10),(9,10),(11,10),(12,10),(13,10),(14,10),
        (15,10),(18,10),(19,10),(20,10),
      ),
     (
        (6,1),(19,4),(1,6),(3,8),(10,8),(17,8),(10,10),(3,12),(10,12),(17,12),(1,14),(19,16),
        (6,19),
      ),
     (2,2), (2,17), "mirror_y"),
    ("vault", 24, 24,
     (
        (8,8),(9,8),(10,8),(11,8),(12,8),(13,8),(14,8),(15,8),(8,9),(15,9),(8,10),(15,10),
        (8,11),(15,12),(8,13),(15,13),(8,14),(15,14),(8,15),(9,15),(10,15),(11,15),(12,15),
        (13,15),(14,15),(15,15),
      ),
     (
        (19,1),(22,1),(10,10),(11,10),(12,10),(11,13),(12,13),(13,13),(1,22),(4,22),
      ),
     (2,19), (20,3), "rot180"),
)

MAP_NAMES = tuple(_d[0] for _d in _DATA)

# fingerprint (width, height, core_x, core_y, team) -> fully resolved record.
# Verified unique across all 15 maps x both teams, so this is a single dict hit.
_BY_FP = {}
_BY_NAME = {}

for _name, _w, _h, _walls, _ore, _ca, _cb, _sym in _DATA:
    _wf = frozenset(_walls)
    _ta = (_ca, (_ca[0] + 1, _ca[1]), (_ca[0], _ca[1] + 1), (_ca[0] + 1, _ca[1] + 1))
    _tb = (_cb, (_cb[0] + 1, _cb[1]), (_cb[0], _cb[1] + 1), (_cb[0] + 1, _cb[1] + 1))
    _ra = {"name": _name, "width": _w, "height": _h, "walls": _wf, "ore": _ore,
           "own_core": _ca, "enemy_core": _cb,
           "own_core_tiles": _ta, "enemy_core_tiles": _tb, "symmetry": _sym}
    _rb = {"name": _name, "width": _w, "height": _h, "walls": _wf, "ore": _ore,
           "own_core": _cb, "enemy_core": _ca,
           "own_core_tiles": _tb, "enemy_core_tiles": _ta, "symmetry": _sym}
    _BY_FP[(_w, _h, _ca[0], _ca[1], "a")] = _ra
    _BY_FP[(_w, _h, _cb[0], _cb[1], "b")] = _rb
    _BY_NAME[_name] = (_ra, _rb)

del _name, _w, _h, _walls, _ore, _ca, _cb, _sym, _wf, _ta, _tb, _ra, _rb


def identify(width, height, core_pos, team):
    """Return the map record dict for this game, or None if unknown.

    ``core_pos`` is OUR core's reported Position (x, y). ``team`` is 'a' or 'b'.
    O(1): one tuple build plus one dict lookup. Never raises -- callers get None and
    fall back to their no-atlas path.
    """
    try:
        t = team if type(team) is str else str(team)
        t = t.strip().lower()
        if t.endswith("a"):
            t = "a"
        elif t.endswith("b"):
            t = "b"
        else:
            return None
        return _BY_FP.get((int(width), int(height), int(core_pos[0]), int(core_pos[1]), t))
    except Exception:
        return None


def mirror(record, pos):
    """Map ``pos`` to the matching tile in the other half, per this map's symmetry.

    Returns a plain ``(x, y)`` tuple. Applying it twice is the identity.
    """
    try:
        x = int(pos[0])
        y = int(pos[1])
        w = record["width"]
        h = record["height"]
        s = record["symmetry"]
        if s == "rot180":
            return (w - 1 - x, h - 1 - y)
        if s == "mirror_x":
            return (w - 1 - x, y)
        if s == "mirror_y":
            return (x, h - 1 - y)
        return (h - 1 - y, w - 1 - x)
    except Exception:
        return None


def by_name(name, team):
    """Offline lookup by map name (for tools and tests). None if unknown."""
    pair = _BY_NAME.get(name)
    if pair is None:
        return None
    return pair[0] if str(team).strip().lower().endswith("a") else pair[1]
