"""GENERATED by tools/build_probe_rush.py -- executes one baked rush plan, verbatim.

One Builder Bot, one Gunner, one Harvester. The Core spawns exactly once and then idles, so nothing
perturbs the cost scale or the timeline. If the model in tools/build_rushplan_dual.py is right, the
match ends on the predicted turn with win_condition == 'core_destroyed'.
"""

from fcode import Controller, Direction, EntityType, Position

DIRS = {
    "NORTH": Direction.NORTH, "EAST": Direction.EAST,
    "SOUTH": Direction.SOUTH, "WEST": Direction.WEST,
}

# (map_w, map_h, core_x, core_y) -> (spawn, ops)
PLAN = {
    (10, 10, 1, 1): ((3, 3), (("MOVE", "SOUTH", 0, 0, ""), ("MOVE", "SOUTH", 0, 0, ""), ("MOVE", "SOUTH", 0, 0, ""), ("MOVE", "SOUTH", 0, 0, ""), ("MOVE", "SOUTH", 0, 0, ""), ("GUNNER", "", 4, 8, "EAST"), ("MOVE", "WEST", 0, 0, ""), ("HARVESTER", "", 3, 8, ""))),
    (10, 10, 7, 7): ((6, 6), (("MOVE", "WEST", 0, 0, ""), ("MOVE", "WEST", 0, 0, ""), ("MOVE", "WEST", 0, 0, ""), ("MOVE", "WEST", 0, 0, ""), ("MOVE", "WEST", 0, 0, ""), ("GUNNER", "", 1, 5, "NORTH"), ("MOVE", "WEST", 0, 0, ""), ("HARVESTER", "", 1, 6, ""))),
    (12, 12, 1, 8): ((3, 7), (("MOVE", "NORTH", 0, 0, ""), ("MOVE", "NORTH", 0, 0, ""), ("MOVE", "NORTH", 0, 0, ""), ("MOVE", "NORTH", 0, 0, ""), ("MOVE", "NORTH", 0, 0, ""), ("MOVE", "NORTH", 0, 0, ""), ("MOVE", "EAST", 0, 0, ""), ("MOVE", "EAST", 0, 0, ""), ("MOVE", "EAST", 0, 0, ""), ("MOVE", "EAST", 0, 0, ""), ("MOVE", "EAST", 0, 0, ""), ("MOVE", "EAST", 0, 0, ""), ("GUNNER", "", 10, 1, "SOUTH"), ("MOVE", "NORTH", 0, 0, ""), ("HARVESTER", "", 10, 0, ""))),
    (12, 12, 9, 2): ((8, 4), (("MOVE", "SOUTH", 0, 0, ""), ("MOVE", "SOUTH", 0, 0, ""), ("MOVE", "SOUTH", 0, 0, ""), ("MOVE", "SOUTH", 0, 0, ""), ("MOVE", "SOUTH", 0, 0, ""), ("MOVE", "SOUTH", 0, 0, ""), ("MOVE", "WEST", 0, 0, ""), ("MOVE", "WEST", 0, 0, ""), ("MOVE", "WEST", 0, 0, ""), ("MOVE", "WEST", 0, 0, ""), ("MOVE", "WEST", 0, 0, ""), ("MOVE", "WEST", 0, 0, ""), ("GUNNER", "", 1, 10, "NORTH"), ("MOVE", "SOUTH", 0, 0, ""), ("HARVESTER", "", 1, 11, ""))),
    (14, 18, 2, 2): ((4, 4), (("MOVE", "EAST", 0, 0, ""), ("MOVE", "EAST", 0, 0, ""), ("MOVE", "SOUTH", 0, 0, ""), ("MOVE", "SOUTH", 0, 0, ""), ("MOVE", "SOUTH", 0, 0, ""), ("MOVE", "SOUTH", 0, 0, ""), ("MOVE", "SOUTH", 0, 0, ""), ("MOVE", "SOUTH", 0, 0, ""), ("MOVE", "SOUTH", 0, 0, ""), ("MOVE", "SOUTH", 0, 0, ""), ("MOVE", "SOUTH", 0, 0, ""), ("MOVE", "SOUTH", 0, 0, ""), ("MOVE", "SOUTH", 0, 0, ""), ("MOVE", "WEST", 0, 0, ""), ("GUNNER", "", 6, 15, "WEST"), ("MOVE", "SOUTH", 0, 0, ""), ("HARVESTER", "", 6, 16, ""))),
    (14, 18, 2, 14): ((4, 13), (("MOVE", "NORTH", 0, 0, ""), ("MOVE", "NORTH", 0, 0, ""), ("MOVE", "NORTH", 0, 0, ""), ("MOVE", "EAST", 0, 0, ""), ("MOVE", "EAST", 0, 0, ""), ("MOVE", "NORTH", 0, 0, ""), ("MOVE", "NORTH", 0, 0, ""), ("MOVE", "NORTH", 0, 0, ""), ("MOVE", "NORTH", 0, 0, ""), ("MOVE", "NORTH", 0, 0, ""), ("MOVE", "NORTH", 0, 0, ""), ("MOVE", "NORTH", 0, 0, ""), ("MOVE", "NORTH", 0, 0, ""), ("MOVE", "WEST", 0, 0, ""), ("GUNNER", "", 6, 2, "WEST"), ("MOVE", "NORTH", 0, 0, ""), ("HARVESTER", "", 6, 1, ""))),
    (16, 16, 2, 11): ((4, 10), (("MOVE", "NORTH", 0, 0, ""), ("MOVE", "NORTH", 0, 0, ""), ("MOVE", "EAST", 0, 0, ""), ("MOVE", "EAST", 0, 0, ""), ("MOVE", "NORTH", 0, 0, ""), ("MOVE", "NORTH", 0, 0, ""), ("MOVE", "EAST", 0, 0, ""), ("MOVE", "EAST", 0, 0, ""), ("MOVE", "NORTH", 0, 0, ""), ("MOVE", "NORTH", 0, 0, ""), ("MOVE", "NORTH", 0, 0, ""), ("MOVE", "EAST", 0, 0, ""), ("GUNNER", "", 10, 3, "EAST"), ("MOVE", "NORTH", 0, 0, ""), ("HARVESTER", "", 10, 2, ""))),
    (16, 16, 12, 3): ((11, 5), (("MOVE", "SOUTH", 0, 0, ""), ("MOVE", "SOUTH", 0, 0, ""), ("MOVE", "WEST", 0, 0, ""), ("MOVE", "WEST", 0, 0, ""), ("MOVE", "SOUTH", 0, 0, ""), ("MOVE", "SOUTH", 0, 0, ""), ("MOVE", "WEST", 0, 0, ""), ("MOVE", "WEST", 0, 0, ""), ("MOVE", "SOUTH", 0, 0, ""), ("MOVE", "SOUTH", 0, 0, ""), ("MOVE", "SOUTH", 0, 0, ""), ("MOVE", "WEST", 0, 0, ""), ("GUNNER", "", 5, 12, "WEST"), ("MOVE", "SOUTH", 0, 0, ""), ("HARVESTER", "", 5, 13, ""))),
    (18, 18, 2, 14): ((4, 13), (("MOVE", "NORTH", 0, 0, ""), ("MOVE", "NORTH", 0, 0, ""), ("MOVE", "NORTH", 0, 0, ""), ("MOVE", "NORTH", 0, 0, ""), ("MOVE", "NORTH", 0, 0, ""), ("MOVE", "NORTH", 0, 0, ""), ("MOVE", "NORTH", 0, 0, ""), ("MOVE", "NORTH", 0, 0, ""), ("MOVE", "NORTH", 0, 0, ""), ("MOVE", "NORTH", 0, 0, ""), ("MOVE", "NORTH", 0, 0, ""), ("MOVE", "EAST", 0, 0, ""), ("MOVE", "EAST", 0, 0, ""), ("MOVE", "EAST", 0, 0, ""), ("MOVE", "EAST", 0, 0, ""), ("MOVE", "EAST", 0, 0, ""), ("MOVE", "EAST", 0, 0, ""), ("MOVE", "EAST", 0, 0, ""), ("GUNNER", "", 12, 2, "EAST"), ("MOVE", "NORTH", 0, 0, ""), ("HARVESTER", "", 12, 1, ""))),
    (18, 18, 14, 2): ((13, 4), (("MOVE", "SOUTH", 0, 0, ""), ("MOVE", "SOUTH", 0, 0, ""), ("MOVE", "SOUTH", 0, 0, ""), ("MOVE", "SOUTH", 0, 0, ""), ("MOVE", "SOUTH", 0, 0, ""), ("MOVE", "SOUTH", 0, 0, ""), ("MOVE", "SOUTH", 0, 0, ""), ("MOVE", "SOUTH", 0, 0, ""), ("MOVE", "SOUTH", 0, 0, ""), ("MOVE", "SOUTH", 0, 0, ""), ("MOVE", "SOUTH", 0, 0, ""), ("MOVE", "WEST", 0, 0, ""), ("MOVE", "WEST", 0, 0, ""), ("MOVE", "WEST", 0, 0, ""), ("MOVE", "WEST", 0, 0, ""), ("MOVE", "WEST", 0, 0, ""), ("MOVE", "WEST", 0, 0, ""), ("MOVE", "WEST", 0, 0, ""), ("GUNNER", "", 5, 15, "WEST"), ("MOVE", "SOUTH", 0, 0, ""), ("HARVESTER", "", 5, 16, ""))),
    (20, 20, 2, 15): ((3, 14), (("MOVE", "NORTH", 0, 0, ""), ("MOVE", "NORTH", 0, 0, ""), ("MOVE", "NORTH", 0, 0, ""), ("MOVE", "NORTH", 0, 0, ""), ("MOVE", "NORTH", 0, 0, ""), ("MOVE", "NORTH", 0, 0, ""), ("MOVE", "NORTH", 0, 0, ""), ("MOVE", "NORTH", 0, 0, ""), ("MOVE", "NORTH", 0, 0, ""), ("MOVE", "NORTH", 0, 0, ""), ("MOVE", "NORTH", 0, 0, ""), ("MOVE", "NORTH", 0, 0, ""), ("MOVE", "EAST", 0, 0, ""), ("MOVE", "EAST", 0, 0, ""), ("MOVE", "EAST", 0, 0, ""), ("MOVE", "EAST", 0, 0, ""), ("MOVE", "EAST", 0, 0, ""), ("MOVE", "EAST", 0, 0, ""), ("MOVE", "EAST", 0, 0, ""), ("MOVE", "EAST", 0, 0, ""), ("MOVE", "EAST", 0, 0, ""), ("MOVE", "EAST", 0, 0, ""), ("MOVE", "EAST", 0, 0, ""), ("MOVE", "EAST", 0, 0, ""), ("MOVE", "EAST", 0, 0, ""), ("GUNNER", "", 17, 2, "SOUTH"), ("MOVE", "NORTH", 0, 0, ""), ("HARVESTER", "", 17, 1, ""))),
    (20, 20, 16, 3): ((16, 5), (("MOVE", "SOUTH", 0, 0, ""), ("MOVE", "SOUTH", 0, 0, ""), ("MOVE", "SOUTH", 0, 0, ""), ("MOVE", "SOUTH", 0, 0, ""), ("MOVE", "SOUTH", 0, 0, ""), ("MOVE", "SOUTH", 0, 0, ""), ("MOVE", "SOUTH", 0, 0, ""), ("MOVE", "SOUTH", 0, 0, ""), ("MOVE", "SOUTH", 0, 0, ""), ("MOVE", "SOUTH", 0, 0, ""), ("MOVE", "SOUTH", 0, 0, ""), ("MOVE", "SOUTH", 0, 0, ""), ("MOVE", "WEST", 0, 0, ""), ("MOVE", "WEST", 0, 0, ""), ("MOVE", "WEST", 0, 0, ""), ("MOVE", "WEST", 0, 0, ""), ("MOVE", "WEST", 0, 0, ""), ("MOVE", "WEST", 0, 0, ""), ("MOVE", "WEST", 0, 0, ""), ("MOVE", "WEST", 0, 0, ""), ("MOVE", "WEST", 0, 0, ""), ("MOVE", "WEST", 0, 0, ""), ("MOVE", "WEST", 0, 0, ""), ("MOVE", "WEST", 0, 0, ""), ("MOVE", "WEST", 0, 0, ""), ("GUNNER", "", 2, 17, "NORTH"), ("MOVE", "SOUTH", 0, 0, ""), ("HARVESTER", "", 2, 18, ""))),
    (20, 26, 2, 2): ((4, 4), (("MOVE", "SOUTH", 0, 0, ""), ("MOVE", "SOUTH", 0, 0, ""), ("MOVE", "SOUTH", 0, 0, ""), ("MOVE", "SOUTH", 0, 0, ""), ("MOVE", "SOUTH", 0, 0, ""), ("MOVE", "SOUTH", 0, 0, ""), ("MOVE", "SOUTH", 0, 0, ""), ("MOVE", "SOUTH", 0, 0, ""), ("MOVE", "SOUTH", 0, 0, ""), ("MOVE", "SOUTH", 0, 0, ""), ("MOVE", "SOUTH", 0, 0, ""), ("MOVE", "SOUTH", 0, 0, ""), ("MOVE", "SOUTH", 0, 0, ""), ("MOVE", "SOUTH", 0, 0, ""), ("MOVE", "WEST", 0, 0, ""), ("MOVE", "WEST", 0, 0, ""), ("GUNNER", "", 2, 19, "SOUTH"), ("MOVE", "WEST", 0, 0, ""), ("HARVESTER", "", 1, 19, ""))),
    (20, 26, 2, 22): ((4, 21), (("MOVE", "NORTH", 0, 0, ""), ("MOVE", "NORTH", 0, 0, ""), ("MOVE", "NORTH", 0, 0, ""), ("MOVE", "NORTH", 0, 0, ""), ("MOVE", "NORTH", 0, 0, ""), ("MOVE", "NORTH", 0, 0, ""), ("MOVE", "NORTH", 0, 0, ""), ("MOVE", "NORTH", 0, 0, ""), ("MOVE", "NORTH", 0, 0, ""), ("MOVE", "NORTH", 0, 0, ""), ("MOVE", "NORTH", 0, 0, ""), ("MOVE", "NORTH", 0, 0, ""), ("MOVE", "NORTH", 0, 0, ""), ("MOVE", "NORTH", 0, 0, ""), ("MOVE", "WEST", 0, 0, ""), ("MOVE", "WEST", 0, 0, ""), ("GUNNER", "", 2, 6, "NORTH"), ("MOVE", "WEST", 0, 0, ""), ("HARVESTER", "", 1, 6, ""))),
    (21, 21, 2, 2): ((3, 4), (("MOVE", "SOUTH", 0, 0, ""), ("MOVE", "SOUTH", 0, 0, ""), ("MOVE", "SOUTH", 0, 0, ""), ("MOVE", "SOUTH", 0, 0, ""), ("MOVE", "SOUTH", 0, 0, ""), ("MOVE", "SOUTH", 0, 0, ""), ("MOVE", "SOUTH", 0, 0, ""), ("MOVE", "SOUTH", 0, 0, ""), ("MOVE", "SOUTH", 0, 0, ""), ("MOVE", "WEST", 0, 0, ""), ("GUNNER", "", 2, 14, "SOUTH"), ("MOVE", "WEST", 0, 0, ""), ("HARVESTER", "", 1, 14, ""))),
    (21, 21, 2, 17): ((3, 16), (("MOVE", "NORTH", 0, 0, ""), ("MOVE", "NORTH", 0, 0, ""), ("MOVE", "NORTH", 0, 0, ""), ("MOVE", "NORTH", 0, 0, ""), ("MOVE", "NORTH", 0, 0, ""), ("MOVE", "NORTH", 0, 0, ""), ("MOVE", "NORTH", 0, 0, ""), ("MOVE", "NORTH", 0, 0, ""), ("MOVE", "NORTH", 0, 0, ""), ("MOVE", "WEST", 0, 0, ""), ("GUNNER", "", 2, 6, "NORTH"), ("MOVE", "WEST", 0, 0, ""), ("HARVESTER", "", 1, 6, ""))),
    (22, 22, 2, 17): ((4, 16), (("MOVE", "NORTH", 0, 0, ""), ("MOVE", "NORTH", 0, 0, ""), ("MOVE", "NORTH", 0, 0, ""), ("MOVE", "NORTH", 0, 0, ""), ("MOVE", "NORTH", 0, 0, ""), ("MOVE", "NORTH", 0, 0, ""), ("MOVE", "EAST", 0, 0, ""), ("MOVE", "EAST", 0, 0, ""), ("MOVE", "EAST", 0, 0, ""), ("MOVE", "EAST", 0, 0, ""), ("MOVE", "EAST", 0, 0, ""), ("MOVE", "EAST", 0, 0, ""), ("MOVE", "EAST", 0, 0, ""), ("MOVE", "EAST", 0, 0, ""), ("MOVE", "EAST", 0, 0, ""), ("MOVE", "EAST", 0, 0, ""), ("MOVE", "EAST", 0, 0, ""), ("MOVE", "EAST", 0, 0, ""), ("MOVE", "NORTH", 0, 0, ""), ("MOVE", "NORTH", 0, 0, ""), ("MOVE", "EAST", 0, 0, ""), ("MOVE", "NORTH", 0, 0, ""), ("GUNNER", "", 18, 7, "NORTH"), ("MOVE", "NORTH", 0, 0, ""), ("HARVESTER", "", 17, 7, ""))),
    (22, 22, 18, 3): ((17, 5), (("MOVE", "SOUTH", 0, 0, ""), ("MOVE", "SOUTH", 0, 0, ""), ("MOVE", "SOUTH", 0, 0, ""), ("MOVE", "SOUTH", 0, 0, ""), ("MOVE", "SOUTH", 0, 0, ""), ("MOVE", "SOUTH", 0, 0, ""), ("MOVE", "WEST", 0, 0, ""), ("MOVE", "WEST", 0, 0, ""), ("MOVE", "WEST", 0, 0, ""), ("MOVE", "WEST", 0, 0, ""), ("MOVE", "WEST", 0, 0, ""), ("MOVE", "WEST", 0, 0, ""), ("MOVE", "WEST", 0, 0, ""), ("MOVE", "WEST", 0, 0, ""), ("MOVE", "WEST", 0, 0, ""), ("MOVE", "WEST", 0, 0, ""), ("MOVE", "WEST", 0, 0, ""), ("MOVE", "WEST", 0, 0, ""), ("MOVE", "SOUTH", 0, 0, ""), ("MOVE", "SOUTH", 0, 0, ""), ("MOVE", "WEST", 0, 0, ""), ("MOVE", "WEST", 0, 0, ""), ("GUNNER", "", 3, 14, "SOUTH"), ("MOVE", "EAST", 0, 0, ""), ("HARVESTER", "", 4, 14, ""))),
    (24, 24, 2, 2): ((4, 4), (("MOVE", "EAST", 0, 0, ""), ("MOVE", "EAST", 0, 0, ""), ("MOVE", "EAST", 0, 0, ""), ("MOVE", "EAST", 0, 0, ""), ("MOVE", "EAST", 0, 0, ""), ("MOVE", "EAST", 0, 0, ""), ("MOVE", "EAST", 0, 0, ""), ("MOVE", "EAST", 0, 0, ""), ("MOVE", "EAST", 0, 0, ""), ("MOVE", "EAST", 0, 0, ""), ("MOVE", "EAST", 0, 0, ""), ("MOVE", "EAST", 0, 0, ""), ("MOVE", "SOUTH", 0, 0, ""), ("MOVE", "SOUTH", 0, 0, ""), ("MOVE", "SOUTH", 0, 0, ""), ("MOVE", "SOUTH", 0, 0, ""), ("MOVE", "SOUTH", 0, 0, ""), ("MOVE", "SOUTH", 0, 0, ""), ("MOVE", "SOUTH", 0, 0, ""), ("MOVE", "SOUTH", 0, 0, ""), ("MOVE", "SOUTH", 0, 0, ""), ("MOVE", "SOUTH", 0, 0, ""), ("MOVE", "SOUTH", 0, 0, ""), ("MOVE", "SOUTH", 0, 0, ""), ("MOVE", "SOUTH", 0, 0, ""), ("MOVE", "SOUTH", 0, 0, ""), ("MOVE", "SOUTH", 0, 0, ""), ("MOVE", "SOUTH", 0, 0, ""), ("GUNNER", "", 17, 20, "EAST"), ("MOVE", "NORTH", 0, 0, ""), ("CONVEYOR", "", 17, 19, "SOUTH"), ("MOVE", "NORTH", 0, 0, ""), ("CONVEYOR", "", 17, 18, "SOUTH"), ("MOVE", "NORTH", 0, 0, ""), ("HARVESTER", "", 17, 17, ""))),
    (24, 24, 2, 11): ((4, 10), (("MOVE", "NORTH", 0, 0, ""), ("MOVE", "NORTH", 0, 0, ""), ("MOVE", "NORTH", 0, 0, ""), ("MOVE", "EAST", 0, 0, ""), ("MOVE", "EAST", 0, 0, ""), ("MOVE", "EAST", 0, 0, ""), ("MOVE", "EAST", 0, 0, ""), ("MOVE", "EAST", 0, 0, ""), ("MOVE", "EAST", 0, 0, ""), ("MOVE", "EAST", 0, 0, ""), ("MOVE", "EAST", 0, 0, ""), ("MOVE", "EAST", 0, 0, ""), ("MOVE", "EAST", 0, 0, ""), ("MOVE", "EAST", 0, 0, ""), ("MOVE", "EAST", 0, 0, ""), ("MOVE", "EAST", 0, 0, ""), ("MOVE", "EAST", 0, 0, ""), ("MOVE", "EAST", 0, 0, ""), ("MOVE", "EAST", 0, 0, ""), ("MOVE", "EAST", 0, 0, ""), ("GUNNER", "", 21, 8, "SOUTH"), ("MOVE", "EAST", 0, 0, ""), ("CONVEYOR", "", 22, 8, "WEST"), ("MOVE", "WEST", 0, 0, ""), ("HARVESTER", "", 22, 7, ""))),
    (24, 24, 2, 19): ((4, 18), (("MOVE", "NORTH", 0, 0, ""), ("MOVE", "NORTH", 0, 0, ""), ("MOVE", "NORTH", 0, 0, ""), ("MOVE", "NORTH", 0, 0, ""), ("MOVE", "NORTH", 0, 0, ""), ("MOVE", "NORTH", 0, 0, ""), ("MOVE", "NORTH", 0, 0, ""), ("MOVE", "NORTH", 0, 0, ""), ("MOVE", "NORTH", 0, 0, ""), ("MOVE", "NORTH", 0, 0, ""), ("MOVE", "NORTH", 0, 0, ""), ("MOVE", "NORTH", 0, 0, ""), ("MOVE", "NORTH", 0, 0, ""), ("MOVE", "NORTH", 0, 0, ""), ("MOVE", "NORTH", 0, 0, ""), ("MOVE", "NORTH", 0, 0, ""), ("MOVE", "NORTH", 0, 0, ""), ("MOVE", "EAST", 0, 0, ""), ("MOVE", "EAST", 0, 0, ""), ("MOVE", "EAST", 0, 0, ""), ("MOVE", "EAST", 0, 0, ""), ("MOVE", "EAST", 0, 0, ""), ("MOVE", "EAST", 0, 0, ""), ("MOVE", "EAST", 0, 0, ""), ("MOVE", "EAST", 0, 0, ""), ("MOVE", "EAST", 0, 0, ""), ("MOVE", "EAST", 0, 0, ""), ("MOVE", "EAST", 0, 0, ""), ("MOVE", "EAST", 0, 0, ""), ("MOVE", "EAST", 0, 0, ""), ("MOVE", "EAST", 0, 0, ""), ("MOVE", "EAST", 0, 0, ""), ("GUNNER", "", 20, 1, "SOUTH"), ("MOVE", "WEST", 0, 0, ""), ("HARVESTER", "", 19, 1, ""))),
    (24, 24, 20, 3): ((19, 5), (("MOVE", "SOUTH", 0, 0, ""), ("MOVE", "SOUTH", 0, 0, ""), ("MOVE", "SOUTH", 0, 0, ""), ("MOVE", "SOUTH", 0, 0, ""), ("MOVE", "SOUTH", 0, 0, ""), ("MOVE", "SOUTH", 0, 0, ""), ("MOVE", "SOUTH", 0, 0, ""), ("MOVE", "SOUTH", 0, 0, ""), ("MOVE", "SOUTH", 0, 0, ""), ("MOVE", "SOUTH", 0, 0, ""), ("MOVE", "SOUTH", 0, 0, ""), ("MOVE", "SOUTH", 0, 0, ""), ("MOVE", "SOUTH", 0, 0, ""), ("MOVE", "SOUTH", 0, 0, ""), ("MOVE", "SOUTH", 0, 0, ""), ("MOVE", "SOUTH", 0, 0, ""), ("MOVE", "WEST", 0, 0, ""), ("MOVE", "WEST", 0, 0, ""), ("MOVE", "WEST", 0, 0, ""), ("MOVE", "WEST", 0, 0, ""), ("MOVE", "WEST", 0, 0, ""), ("MOVE", "WEST", 0, 0, ""), ("MOVE", "WEST", 0, 0, ""), ("MOVE", "WEST", 0, 0, ""), ("MOVE", "WEST", 0, 0, ""), ("MOVE", "WEST", 0, 0, ""), ("MOVE", "WEST", 0, 0, ""), ("MOVE", "WEST", 0, 0, ""), ("MOVE", "WEST", 0, 0, ""), ("MOVE", "WEST", 0, 0, ""), ("MOVE", "WEST", 0, 0, ""), ("MOVE", "WEST", 0, 0, ""), ("GUNNER", "", 3, 22, "NORTH"), ("MOVE", "EAST", 0, 0, ""), ("HARVESTER", "", 4, 22, ""))),
    (24, 24, 20, 11): ((19, 10), (("MOVE", "NORTH", 0, 0, ""), ("MOVE", "NORTH", 0, 0, ""), ("MOVE", "NORTH", 0, 0, ""), ("MOVE", "WEST", 0, 0, ""), ("MOVE", "WEST", 0, 0, ""), ("MOVE", "WEST", 0, 0, ""), ("MOVE", "WEST", 0, 0, ""), ("MOVE", "WEST", 0, 0, ""), ("MOVE", "WEST", 0, 0, ""), ("MOVE", "WEST", 0, 0, ""), ("MOVE", "WEST", 0, 0, ""), ("MOVE", "WEST", 0, 0, ""), ("MOVE", "WEST", 0, 0, ""), ("MOVE", "WEST", 0, 0, ""), ("MOVE", "WEST", 0, 0, ""), ("MOVE", "WEST", 0, 0, ""), ("MOVE", "WEST", 0, 0, ""), ("MOVE", "WEST", 0, 0, ""), ("MOVE", "WEST", 0, 0, ""), ("MOVE", "WEST", 0, 0, ""), ("GUNNER", "", 2, 8, "SOUTH"), ("MOVE", "WEST", 0, 0, ""), ("CONVEYOR", "", 2, 7, "SOUTH"), ("MOVE", "WEST", 0, 0, ""), ("HARVESTER", "", 1, 7, ""))),
    (24, 24, 20, 20): ((19, 19), (("MOVE", "NORTH", 0, 0, ""), ("MOVE", "NORTH", 0, 0, ""), ("MOVE", "NORTH", 0, 0, ""), ("MOVE", "NORTH", 0, 0, ""), ("MOVE", "NORTH", 0, 0, ""), ("MOVE", "NORTH", 0, 0, ""), ("MOVE", "NORTH", 0, 0, ""), ("MOVE", "NORTH", 0, 0, ""), ("MOVE", "NORTH", 0, 0, ""), ("MOVE", "NORTH", 0, 0, ""), ("MOVE", "NORTH", 0, 0, ""), ("MOVE", "NORTH", 0, 0, ""), ("MOVE", "WEST", 0, 0, ""), ("MOVE", "WEST", 0, 0, ""), ("MOVE", "WEST", 0, 0, ""), ("MOVE", "WEST", 0, 0, ""), ("MOVE", "WEST", 0, 0, ""), ("MOVE", "WEST", 0, 0, ""), ("MOVE", "WEST", 0, 0, ""), ("MOVE", "WEST", 0, 0, ""), ("MOVE", "WEST", 0, 0, ""), ("MOVE", "WEST", 0, 0, ""), ("MOVE", "WEST", 0, 0, ""), ("MOVE", "WEST", 0, 0, ""), ("MOVE", "WEST", 0, 0, ""), ("MOVE", "WEST", 0, 0, ""), ("MOVE", "WEST", 0, 0, ""), ("MOVE", "WEST", 0, 0, ""), ("GUNNER", "", 3, 6, "NORTH"), ("MOVE", "EAST", 0, 0, ""), ("CONVEYOR", "", 4, 6, "WEST"), ("MOVE", "EAST", 0, 0, ""), ("CONVEYOR", "", 5, 6, "WEST"), ("MOVE", "EAST", 0, 0, ""), ("HARVESTER", "", 6, 6, ""))),
    (25, 25, 2, 20): ((4, 19), (("MOVE", "NORTH", 0, 0, ""), ("MOVE", "NORTH", 0, 0, ""), ("MOVE", "NORTH", 0, 0, ""), ("MOVE", "NORTH", 0, 0, ""), ("MOVE", "NORTH", 0, 0, ""), ("MOVE", "NORTH", 0, 0, ""), ("MOVE", "NORTH", 0, 0, ""), ("MOVE", "NORTH", 0, 0, ""), ("MOVE", "NORTH", 0, 0, ""), ("MOVE", "NORTH", 0, 0, ""), ("MOVE", "NORTH", 0, 0, ""), ("MOVE", "EAST", 0, 0, ""), ("MOVE", "EAST", 0, 0, ""), ("MOVE", "EAST", 0, 0, ""), ("MOVE", "EAST", 0, 0, ""), ("MOVE", "EAST", 0, 0, ""), ("MOVE", "EAST", 0, 0, ""), ("MOVE", "EAST", 0, 0, ""), ("MOVE", "EAST", 0, 0, ""), ("MOVE", "EAST", 0, 0, ""), ("MOVE", "EAST", 0, 0, ""), ("MOVE", "EAST", 0, 0, ""), ("MOVE", "EAST", 0, 0, ""), ("MOVE", "EAST", 0, 0, ""), ("MOVE", "EAST", 0, 0, ""), ("MOVE", "EAST", 0, 0, ""), ("MOVE", "EAST", 0, 0, ""), ("MOVE", "EAST", 0, 0, ""), ("MOVE", "EAST", 0, 0, ""), ("GUNNER", "", 22, 7, "NORTH"), ("MOVE", "EAST", 0, 0, ""), ("HARVESTER", "", 23, 7, ""))),
    (25, 25, 21, 3): ((20, 5), (("MOVE", "SOUTH", 0, 0, ""), ("MOVE", "SOUTH", 0, 0, ""), ("MOVE", "SOUTH", 0, 0, ""), ("MOVE", "SOUTH", 0, 0, ""), ("MOVE", "SOUTH", 0, 0, ""), ("MOVE", "SOUTH", 0, 0, ""), ("MOVE", "SOUTH", 0, 0, ""), ("MOVE", "SOUTH", 0, 0, ""), ("MOVE", "SOUTH", 0, 0, ""), ("MOVE", "SOUTH", 0, 0, ""), ("MOVE", "SOUTH", 0, 0, ""), ("MOVE", "WEST", 0, 0, ""), ("MOVE", "WEST", 0, 0, ""), ("MOVE", "WEST", 0, 0, ""), ("MOVE", "WEST", 0, 0, ""), ("MOVE", "WEST", 0, 0, ""), ("MOVE", "WEST", 0, 0, ""), ("MOVE", "WEST", 0, 0, ""), ("MOVE", "WEST", 0, 0, ""), ("MOVE", "WEST", 0, 0, ""), ("MOVE", "WEST", 0, 0, ""), ("MOVE", "WEST", 0, 0, ""), ("MOVE", "WEST", 0, 0, ""), ("MOVE", "WEST", 0, 0, ""), ("MOVE", "WEST", 0, 0, ""), ("MOVE", "WEST", 0, 0, ""), ("MOVE", "WEST", 0, 0, ""), ("MOVE", "WEST", 0, 0, ""), ("MOVE", "WEST", 0, 0, ""), ("GUNNER", "", 2, 17, "SOUTH"), ("MOVE", "WEST", 0, 0, ""), ("HARVESTER", "", 1, 17, ""))),
    (26, 26, 3, 22): ((2, 21), (("MOVE", "NORTH", 0, 0, ""), ("MOVE", "NORTH", 0, 0, ""), ("MOVE", "NORTH", 0, 0, ""), ("MOVE", "NORTH", 0, 0, ""), ("MOVE", "NORTH", 0, 0, ""), ("MOVE", "NORTH", 0, 0, ""), ("MOVE", "NORTH", 0, 0, ""), ("MOVE", "WEST", 0, 0, ""), ("MOVE", "NORTH", 0, 0, ""), ("MOVE", "NORTH", 0, 0, ""), ("MOVE", "NORTH", 0, 0, ""), ("MOVE", "NORTH", 0, 0, ""), ("MOVE", "NORTH", 0, 0, ""), ("MOVE", "NORTH", 0, 0, ""), ("MOVE", "NORTH", 0, 0, ""), ("MOVE", "EAST", 0, 0, ""), ("MOVE", "EAST", 0, 0, ""), ("MOVE", "EAST", 0, 0, ""), ("MOVE", "EAST", 0, 0, ""), ("MOVE", "EAST", 0, 0, ""), ("MOVE", "EAST", 0, 0, ""), ("MOVE", "EAST", 0, 0, ""), ("MOVE", "EAST", 0, 0, ""), ("MOVE", "EAST", 0, 0, ""), ("MOVE", "EAST", 0, 0, ""), ("MOVE", "EAST", 0, 0, ""), ("MOVE", "EAST", 0, 0, ""), ("MOVE", "EAST", 0, 0, ""), ("MOVE", "EAST", 0, 0, ""), ("MOVE", "EAST", 0, 0, ""), ("MOVE", "NORTH", 0, 0, ""), ("MOVE", "NORTH", 0, 0, ""), ("MOVE", "NORTH", 0, 0, ""), ("MOVE", "NORTH", 0, 0, ""), ("MOVE", "NORTH", 0, 0, ""), ("MOVE", "EAST", 0, 0, ""), ("GUNNER", "", 18, 2, "EAST"), ("MOVE", "NORTH", 0, 0, ""), ("HARVESTER", "", 18, 1, ""))),
    (26, 26, 21, 2): ((23, 4), (("MOVE", "EAST", 0, 0, ""), ("MOVE", "SOUTH", 0, 0, ""), ("MOVE", "SOUTH", 0, 0, ""), ("MOVE", "SOUTH", 0, 0, ""), ("MOVE", "SOUTH", 0, 0, ""), ("MOVE", "SOUTH", 0, 0, ""), ("MOVE", "SOUTH", 0, 0, ""), ("MOVE", "SOUTH", 0, 0, ""), ("MOVE", "SOUTH", 0, 0, ""), ("MOVE", "SOUTH", 0, 0, ""), ("MOVE", "SOUTH", 0, 0, ""), ("MOVE", "SOUTH", 0, 0, ""), ("MOVE", "SOUTH", 0, 0, ""), ("MOVE", "SOUTH", 0, 0, ""), ("MOVE", "SOUTH", 0, 0, ""), ("MOVE", "WEST", 0, 0, ""), ("MOVE", "WEST", 0, 0, ""), ("MOVE", "WEST", 0, 0, ""), ("MOVE", "WEST", 0, 0, ""), ("MOVE", "WEST", 0, 0, ""), ("MOVE", "WEST", 0, 0, ""), ("MOVE", "WEST", 0, 0, ""), ("MOVE", "WEST", 0, 0, ""), ("MOVE", "WEST", 0, 0, ""), ("MOVE", "WEST", 0, 0, ""), ("MOVE", "WEST", 0, 0, ""), ("MOVE", "WEST", 0, 0, ""), ("MOVE", "WEST", 0, 0, ""), ("MOVE", "WEST", 0, 0, ""), ("MOVE", "WEST", 0, 0, ""), ("MOVE", "SOUTH", 0, 0, ""), ("MOVE", "SOUTH", 0, 0, ""), ("MOVE", "SOUTH", 0, 0, ""), ("MOVE", "SOUTH", 0, 0, ""), ("MOVE", "SOUTH", 0, 0, ""), ("MOVE", "WEST", 0, 0, ""), ("GUNNER", "", 7, 23, "WEST"), ("MOVE", "SOUTH", 0, 0, ""), ("HARVESTER", "", 7, 24, ""))),
    (28, 20, 2, 8): ((4, 7), (("MOVE", "EAST", 0, 0, ""), ("MOVE", "EAST", 0, 0, ""), ("MOVE", "EAST", 0, 0, ""), ("MOVE", "EAST", 0, 0, ""), ("MOVE", "EAST", 0, 0, ""), ("MOVE", "EAST", 0, 0, ""), ("MOVE", "EAST", 0, 0, ""), ("MOVE", "EAST", 0, 0, ""), ("MOVE", "EAST", 0, 0, ""), ("MOVE", "EAST", 0, 0, ""), ("MOVE", "EAST", 0, 0, ""), ("MOVE", "EAST", 0, 0, ""), ("MOVE", "EAST", 0, 0, ""), ("MOVE", "EAST", 0, 0, ""), ("MOVE", "EAST", 0, 0, ""), ("MOVE", "EAST", 0, 0, ""), ("MOVE", "EAST", 0, 0, ""), ("MOVE", "EAST", 0, 0, ""), ("MOVE", "EAST", 0, 0, ""), ("MOVE", "EAST", 0, 0, ""), ("MOVE", "EAST", 0, 0, ""), ("MOVE", "NORTH", 0, 0, ""), ("GUNNER", "", 25, 5, "SOUTH"), ("MOVE", "EAST", 0, 0, ""), ("HARVESTER", "", 26, 5, ""))),
    (28, 20, 24, 8): ((23, 7), (("MOVE", "WEST", 0, 0, ""), ("MOVE", "WEST", 0, 0, ""), ("MOVE", "WEST", 0, 0, ""), ("MOVE", "WEST", 0, 0, ""), ("MOVE", "WEST", 0, 0, ""), ("MOVE", "WEST", 0, 0, ""), ("MOVE", "WEST", 0, 0, ""), ("MOVE", "WEST", 0, 0, ""), ("MOVE", "WEST", 0, 0, ""), ("MOVE", "WEST", 0, 0, ""), ("MOVE", "WEST", 0, 0, ""), ("MOVE", "WEST", 0, 0, ""), ("MOVE", "WEST", 0, 0, ""), ("MOVE", "WEST", 0, 0, ""), ("MOVE", "WEST", 0, 0, ""), ("MOVE", "WEST", 0, 0, ""), ("MOVE", "WEST", 0, 0, ""), ("MOVE", "WEST", 0, 0, ""), ("MOVE", "WEST", 0, 0, ""), ("MOVE", "WEST", 0, 0, ""), ("MOVE", "WEST", 0, 0, ""), ("MOVE", "NORTH", 0, 0, ""), ("GUNNER", "", 2, 5, "SOUTH"), ("MOVE", "WEST", 0, 0, ""), ("HARVESTER", "", 1, 5, ""))),
}


class Player:
    def __init__(self):
        self.plan = None
        self.spawned = False
        self.i = 0
        self.looked = False

    def _lookup(self, ct):
        if self.looked:
            return self.plan
        self.looked = True
        try:
            p = ct.get_position()
            self.plan = PLAN.get((ct.get_map_width(), ct.get_map_height(), p.x, p.y))
        except Exception:
            self.plan = None
        return self.plan

    def run(self, ct: Controller) -> None:
        try:
            et = ct.get_entity_type()
        except Exception:
            return
        try:
            if et == EntityType.CORE:
                self._core(ct)
            elif et == EntityType.BUILDER_BOT:
                self._builder(ct)
            elif et == EntityType.GUNNER:
                self._gunner(ct)
        except Exception:
            pass

    def _core(self, ct):
        if self.spawned:
            return
        p = self._lookup(ct)
        if p is None:
            return
        self.spawned = True
        ct.spawn_builder(Position(p[0][0], p[0][1]))

    def _builder(self, ct):
        if self.plan is None:
            # builders get their own Player instance; re-derive from the store-free constant table
            for key, val in PLAN.items():
                if key[0] == ct.get_map_width() and key[1] == ct.get_map_height():
                    pos = ct.get_position()
                    if abs(pos.x - key[2]) <= 3 and abs(pos.y - key[3]) <= 3:
                        self.plan = val
                        break
            if self.plan is None:
                return
        ops = self.plan[1]
        if self.i >= len(ops):
            return
        op, arg, x, y, facing = ops[self.i]
        try:
            if op == "MOVE":
                ct.move(DIRS[arg])
            elif op == "GUNNER":
                ct.build_gunner(Position(x, y), DIRS[facing])
            elif op == "CONVEYOR":
                ct.build_conveyor(Position(x, y), DIRS[facing])
            elif op == "HARVESTER":
                ct.build_harvester(Position(x, y))
        except Exception:
            return
        self.i += 1

    def _gunner(self, ct):
        try:
            t = ct.get_gunner_target()
        except Exception:
            return
        if t is None:
            return
        try:
            if ct.can_fire(t):
                ct.fire(t)
        except Exception:
            return
