"""Extract Pantheon's per-unit actions from a real replay into a script.

The script is replayed verbatim by bots/luc/pantheon_puppet for the first N
rounds, after which the replica takes over. That isolates "what does the bot
decide from *this* state" from "how did it get here".

Usage: make_script.py <mapname>  ->  writes bots/luc/pantheon_puppet/script_data.py
"""
import glob, os, sys
import decode

REPO = "/home/Ucals/projects/florent-code-league-llm-rl"
S = ("/tmp/claude-1000/-home-Ucals-projects-florent-code-league-llm-rl/"
     "05d146e7-6b75-4d33-a413-788991e5ff01/scratchpad")


def local_maps():
    out = {}
    for f in sorted(glob.glob(f"{REPO}/maps/*.map26")):
        m = decode.parse(open(f, "rb").read(), "Map")
        g = tuple(tuple(r.get("tiles", [])) for r in m.get("rows", []))
        out[(m.get("width"), m.get("height"), g)] = os.path.basename(f).replace(".map26", "")
    return out


def build(path, want):
    real = decode.decode(path)
    pan = "TEAM_A" if real["winner"] == "TEAM_A" else "TEAM_B"
    cores = {c.get("team", "TEAM_A"): c for c in real["map"]["cores"]}
    core_id = cores[pan]["id"]
    owner = {c["id"]: c.get("team", "TEAM_A") for c in real["map"]["cores"]}
    posn = {c["id"]: c["pos"] for c in real["map"]["cores"]}
    kind = {c["id"]: "core" for c in real["map"]["cores"]}

    script = {}          # round -> list of (unit_id, action tuple)
    for rnd, ups in enumerate(real["turns"]):
        acts = []
        # index this round's placements so a builderBuild can be typed
        placed = {}
        for u in ups:
            if "placeEntity" in u:
                e = u["placeEntity"]["entity"]
                k = decode.entity_kind(e)
                facing = None
                for slot in ("gunner", "sentinel", "conveyor", "splitter"):
                    if slot in e:
                        facing = e[slot].get("direction")
                placed[decode.pos(e.get("position", {}))] = (
                    k, e.get("team", "TEAM_A"), e["id"], facing)
        for u in ups:
            if "placeEntity" in u:
                e = u["placeEntity"]["entity"]
                t = e.get("team", "TEAM_A")
                owner[e["id"]] = t
                p = decode.pos(e.get("position", {}))
                posn[e["id"]] = p
                kind[e["id"]] = decode.entity_kind(e)
                # A Builder appearing with no builderBuild naming it was
                # spawned by the Core.
                if t == pan and kind[e["id"]] == "builder":
                    named = any("builderBuild" in x
                                and decode.pos(x["builderBuild"].get("target", {})) == p
                                for x in ups)
                    if not named:
                        acts.append((core_id, ("spawn", p)))
            elif "builderBuild" in u:
                bb = u["builderBuild"]
                if owner.get(bb["id"]) != pan:
                    continue
                target = decode.pos(bb.get("target", {}))
                info = placed.get(target)
                if info:
                    acts.append((bb["id"], ("build", info[0], target, info[3])))
            elif "moveBuilderBot" in u:
                mv = u["moveBuilderBot"]
                i = mv["id"]
                to = decode.pos(mv.get("to", {}))
                frm = posn.get(i)
                posn[i] = to
                if owner.get(i) != pan or frm is None:
                    continue
                if max(abs(to[0]-frm[0]), abs(to[1]-frm[1])) > 1:
                    acts.append((None, ("launch", frm, to)))   # launcher acts
                else:
                    acts.append((i, ("move", to)))
            elif "coreConvertAmmo" in u:
                cv = u["coreConvertAmmo"]
                if cv.get("team", "TEAM_A") == pan:
                    acts.append((core_id, ("convert", cv.get("amount", 0))))
            elif "removeEntity" in u:
                i = u["removeEntity"]["id"]
                if owner.get(i) == pan and kind.get(i) == "launcher":
                    acts.append((i, ("selfdestruct",)))
        if acts:
            script[rnd] = acts
    return pan, script


def main():
    want = sys.argv[1]
    maps = local_maps()
    for rp in sorted(glob.glob(f"{S}/pantheon/vs_us_v20/*.replay26")):
        r = decode.decode(rp)
        m = r["map"]
        key = (m["width"], m["height"], tuple(tuple(x) for x in m["grid"]))
        if maps.get(key) != want:
            continue
        pan, script = build(rp, want)
        out = f"{REPO}/bots/luc/pantheon_puppet/script_data.py"
        with open(out, "w") as fh:
            fh.write('"""Generated by tools/pantheon_analysis/make_script.py."""\n')
            fh.write(f"MAP = {want!r}\n")
            fh.write(f"SEAT = {pan!r}\n")
            fh.write("SCRIPT = {\n")
            for rnd in sorted(script):
                fh.write(f"    {rnd}: {script[rnd]!r},\n")
            fh.write("}\n")
        print(f"{want}: seat {pan}, {len(script)} scripted rounds -> {out}")
        for rnd in sorted(script)[:8]:
            print(f"  r{rnd}: {script[rnd]}")
        return
    print(f"no real game on {want}")


main()
