"""AUTO-GENERATED by scratchpad/gen_duel.py -- turret first-strike duel, side B.

maps/lab/duel.map26.  Core spawns ONE builder on round 2; the builder
walks to (10, 4), builds a sentinel at (9, 4) facing WEST on round
20, then steps to (10, 3).  Fire mode "duel":
  duel -- the turret only ever fires at the enemy turret tile (6, 4)
  free -- the turret fires at any enemy entity inside its attackable tiles

The CORE reports (reporter=False); everything else is relayed through store
slots, so the report survives the builder and the turret being killed.
"""

from fcode import Controller, Direction, EntityType, Position

SIDE = "B"
SPAWN = Position(12, 4)
BPOS = Position(10, 4)
TPOS = Position(9, 4)
OBS = Position(10, 3)
ETPOS = Position(6, 4)
FACING = Direction.WEST
WALK = [Direction.WEST, Direction.WEST]
SPAWN_ROUND = 2
BUILD_ROUND = 20
RESIGN_ROUND = 60
REPORT = False
TURRET = "sentinel"
MODE = "duel"

# ---- store slots (team-wide, one-round write lag).  All values are +1 so that
# 0 means "never written".
T_SHOTS, T_LASTFIRE, T_FOEHP, T_OWNHP, T_ID, T_SATK, T_FIRST = 0, 1, 2, 3, 4, 5, 6
B_BEAT, B_ID, B_TID, B_BROUND, B_EID, B_EHP, B_OHP, B_FIRST = 7, 8, 9, 10, 11, 12, 13, 14


def _w(ct, slot, val):
    try:
        ct.write_store(slot, max(0, min(4294967295, int(val))))
    except Exception:
        pass


class Player:
    def __init__(self):
        self.err = []
        self.spawned = None
        self.log = []
        self.last = None
        self.step = 0
        self.shots = 0
        self.lastfire = -1
        self.first = None
        self.tid = None

    def run(self, ct: Controller) -> None:
        try:
            self._run(ct)
        except Exception as exc:
            if len(self.err) < 6:
                self.err.append("%s:%s" % (type(exc).__name__, str(exc)[:60]))

    def _run(self, ct):
        et = ct.get_entity_type()
        if et == EntityType.CORE:
            self._core(ct)
        elif et == EntityType.BUILDER_BOT:
            self._builder(ct)
        elif et in (EntityType.SENTINEL, EntityType.GUNNER):
            self._turret(ct)

    # ------------------------------------------------------------------ core
    def _core(self, ct):
        r = ct.get_current_round()
        if self.first is None:
            self.first = r
        if REPORT:
            self._sample(ct, r)
        if self.spawned is None and r >= SPAWN_ROUND:
            if ct.can_spawn(SPAWN):
                self.spawned = ct.spawn_builder(SPAWN)
                return
        try:
            if ct.get_global_ammo() < 500 and ct.can_convert_ammo(50):
                ct.convert_ammo(50)
        except Exception:
            pass

    def _sample(self, ct, r):
        try:
            v = tuple(ct.read_store(i) for i in range(15))
        except Exception:
            return
        if v != self.last:
            d = lambda i: v[i] - 1 if v[i] else None      # noqa: E731
            self.log.append(
                "r%d|sh%s lf%s tfh%s toh%s tid%s|beat%s bid%s btid%s br%s eid%s ehp%s ohp%s"
                % (r, d(T_SHOTS), d(T_LASTFIRE), d(T_FOEHP), d(T_OWNHP), d(T_ID),
                   d(B_BEAT), d(B_ID), d(B_TID), d(B_BROUND), d(B_EID),
                   d(B_EHP), d(B_OHP)))
            self.last = v
        if r >= RESIGN_ROUND:
            ct.resign(self._msg(ct, v))

    def _msg(self, ct, v):
        d = lambda i: v[i] - 1 if v[i] else None          # noqa: E731
        try:
            ammo = ct.get_global_ammo()
        except Exception:
            ammo = -1
        return (
            "CFG side=%s %s mode=%s spawnR=%d buildR=%d coreid=%s corefirst=%s | "
            "bid=%s bfirst=%s builtid=%s buildround=%s turretfirst=%s satk=%s | "
            "shots=%s lastfire=%s ammo=%s | LOG %s | ERR %s"
            % (SIDE, TURRET, MODE, SPAWN_ROUND, BUILD_ROUND,
               ct.get_id(), self.first,
               d(B_ID), d(B_FIRST), d(B_TID), d(B_BROUND), d(T_FIRST), d(T_SATK),
               d(T_SHOTS), d(T_LASTFIRE), ammo,
               " ".join(self.log[:44]), ";".join(self.err[:4]))
        )

    # --------------------------------------------------------------- builder
    def _builder(self, ct):
        r = ct.get_current_round()
        _w(ct, B_BEAT, r + 1)
        _w(ct, B_ID, ct.get_id() + 1)
        if self.first is None:
            self.first = r
            _w(ct, B_FIRST, r + 1)

        # observe both turret tiles at OUR turn (builder id < turret ids, so this
        # is the state at the START of the round)
        for tile, slot in ((TPOS, B_OHP), (ETPOS, B_EHP)):
            try:
                b = ct.get_tile_building_id(tile)
                _w(ct, slot, (ct.get_hp(b) + 1) if b is not None else 0)
                if tile == ETPOS and b is not None:
                    _w(ct, B_EID, b + 1)
            except Exception:
                pass

        if self.step < len(WALK):
            d = WALK[self.step]
            if ct.can_move(d):
                ct.move(d)
                self.step += 1
            return

        if self.step == len(WALK):
            if r < BUILD_ROUND:
                return
            try:
                if TURRET == "sentinel":
                    if not ct.can_build_sentinel(TPOS, FACING):
                        return
                    self.tid = ct.build_sentinel(TPOS, FACING)
                else:
                    if not ct.can_build_gunner(TPOS, FACING):
                        return
                    self.tid = ct.build_gunner(TPOS, FACING)
            except Exception as exc:
                self.err.append("B:%s" % str(exc)[:40])
                return
            _w(ct, B_TID, self.tid + 1)
            _w(ct, B_BROUND, r + 1)
            self.step += 1
            return

        if self.step == len(WALK) + 1:
            if ct.can_move(Direction.NORTH):
                ct.move(Direction.NORTH)
            self.step += 1
            return

    # ---------------------------------------------------------------- turret
    def _turret(self, ct):
        r = ct.get_current_round()
        if self.first is None:
            self.first = r
            _w(ct, T_FIRST, r + 1)
            _w(ct, T_ID, ct.get_id() + 1)
            try:
                _w(ct, T_SATK, len(ct.get_attackable_tiles()) + 1)
            except Exception:
                pass

        foehp = None
        try:
            b = ct.get_tile_building_id(ETPOS)
            if b is not None:
                foehp = ct.get_hp(b)
        except Exception:
            pass
        _w(ct, T_FOEHP, (foehp + 1) if foehp is not None else 0)
        try:
            _w(ct, T_OWNHP, ct.get_hp() + 1)
        except Exception:
            pass

        target = None
        try:
            if ct.can_fire(ETPOS):
                target = ETPOS
            elif MODE == "free":
                me = ct.get_team()
                for p in ct.get_attackable_tiles():
                    try:
                        if ct.can_fire(p):
                            hit = ct.get_tile_building_id(p)
                            if hit is None:
                                hit = ct.get_tile_builder_bot_id(p)
                            if hit is not None and ct.get_team(hit) != me:
                                target = p
                                break
                    except Exception:
                        pass
        except Exception:
            pass
        if target is not None:
            try:
                ct.fire(target)
                self.shots += 1
                self.lastfire = r
            except Exception as exc:
                if len(self.err) < 6:
                    self.err.append("F:%s" % str(exc)[:40])
        _w(ct, T_SHOTS, self.shots + 1)
        _w(ct, T_LASTFIRE, self.lastfire + 1)
