"""Deployable RL bot -- generated by rl/export_pure_python.py, do not hand-edit.

Pure stdlib + fcode only (no torch/numpy/sockets): this is the version meant for
`fcode submit`. It re-implements rl/policy.py's per-entity-type forward pass by
hand over weights baked into weights.json at export time, and always acts greedily
(argmax), since a submitted bot should play its best policy rather than explore.
"""

from __future__ import annotations

import json
import sys
from pathlib import Path

_HERE = Path(__file__).resolve().parent
if str(_HERE) not in sys.path:
    sys.path.insert(0, str(_HERE))

from fcode import Controller

from features import RICH_TYPES, encode_observation, apply_action
from map_memory import MapMemory

with open(_HERE / "weights.json") as _f:
    _WEIGHTS = json.load(_f)


def _linear(x: list[float], layer: dict, relu: bool) -> list[float]:
    w, b = layer["w"], layer["b"]
    out = [bj + sum(xi * wi for xi, wi in zip(x, wrow)) for bj, wrow in zip(b, w)]
    if relu:
        out = [v if v > 0.0 else 0.0 for v in out]
    return out


def _argmax(xs: list[float]) -> int:
    best_i, best_v = 0, xs[0]
    for i in range(1, len(xs)):
        if xs[i] > best_v:
            best_i, best_v = i, xs[i]
    return best_i


class Player:
    def __init__(self) -> None:
        self._memory: MapMemory | None = None

    def run(self, ct: Controller) -> None:
        etype = ct.get_entity_type()
        if etype in RICH_TYPES and self._memory is None:
            self._memory = MapMemory()
        obs = encode_observation(ct, self._memory)

        weights = _WEIGHTS[etype.value]
        h1 = _linear(obs, weights["body"][0], relu=True)
        h2 = _linear(h1, weights["body"][1], relu=True)
        logits = _linear(h2, weights["actor"], relu=False)
        action = _argmax(logits)

        apply_action(ct, etype, action)
