"""Decide whether a bot is a fair entrant by reading its code, not its directory.

Fairness was inferred from the path -- a bot under `unfair/` was unfair. That is a convention,
and conventions drift: Elias' cand/ snapshots and every version of Luc's tempest_reinforcements
carry the same offline map atlas as bots their own authors filed under `unfair/`, while sitting
in ordinary directories. Eleven entrants were mislabelled on the published ladder.

The signal is an import of a bundled atlas module. Those modules say plainly what they are --
"Published-map oracle deliberately excluded from fair bots", "GENERATED by tools/build_atlas.py
from maps/*.map26" -- and they hand the bot static terrain and the enemy Core before either has
been scouted, which no fog-of-war entrant can know.

A path tag still wins when present, so an author can mark a bot unfair for a reason this cannot
see. This only ever adds unfair flags; it never clears one.
"""

from __future__ import annotations

import io
import re
import subprocess
import tarfile
from functools import lru_cache

from tournament.gitutil import REPO_ROOT

# `import atlas`, `from atlas import ...`, `from atlas_data import ...`.
_ATLAS_IMPORT = re.compile(r"^\s*(?:from\s+(atlas\w*)\s+import|import\s+(atlas\w*))", re.M)


@lru_cache(maxsize=4096)
def uses_offline_atlas(commit: str, path: str) -> bool:
    """True when the bot imports a bundled map atlas at this commit."""
    result = subprocess.run(
        ["git", "archive", f"{commit}:{path}"], cwd=REPO_ROOT, capture_output=True
    )
    if result.returncode != 0:
        return False
    with tarfile.open(fileobj=io.BytesIO(result.stdout)) as archive:
        for member in archive.getmembers():
            if not (member.isfile() and member.name.endswith(".py")):
                continue
            handle = archive.extractfile(member)
            if handle is None:
                continue
            source = handle.read().decode("utf-8", "replace")
            if _ATLAS_IMPORT.search(source):
                return True
    return False


def is_unfair(tags, commit: str, path: str) -> bool:
    """Unfair if the author said so, or if the code reaches for knowledge it cannot observe."""
    if "unfair" in (tags or ()):
        return True
    if not commit or not path:
        return False
    return uses_offline_atlas(commit, path)
