#!/usr/bin/env python
"""Generate ``bots/probe_rush/main.py`` -- a bot that executes exactly one rush plan and nothing
else, so that ``run_game``'s reported ``turns`` IS the measured kill turn.

The whole point is falsifiability: the generator predicts a kill turn from a model; this bot plays
that plan literally, and if the model is right the engine ends the match on the predicted turn with
``win_condition == 'core_destroyed'``.
"""

from __future__ import annotations

import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT / "tools"))
sys.path.insert(0, str(ROOT / "bot"))

import atlas                                    # noqa: E402
from build_rushplan_dual import (               # noqa: E402
    CDELTA, CARD_NAME, Board, analyse,
)


def path_between(bd, a, b, blocked):
    """Cardinal step names from a to b avoiding ``blocked``. () if a == b, None if unreachable."""
    if a == b:
        return ()
    dist = bd.bfs([b], blocked=blocked - {b})
    if a not in dist:
        return None
    steps, cur = [], a
    while cur != b:
        nxt = None
        for d in CDELTA:
            n = (cur[0] + d[0], cur[1] + d[1])
            if n in dist and dist[n] == dist[cur] - 1:
                nxt = (n, d)
                break
        if nxt is None:
            return None
        steps.append(CARD_NAME[nxt[1]])
        cur = nxt[0]
    return tuple(steps)


def build_steps(bd, plan):
    """(spawn_tile, [(op, arg...), ...]) -- one entry per round the builder is busy."""
    stands = plan["stands"]
    blocker = frozenset([plan["g"]])          # only the Gunner blocks movement

    # pick the spawn ring tile that actually realises the modelled walk
    d_from_stand = bd.bfs([stands[0]])
    cands = [(d_from_stand[r], r) for r in sorted(bd.own_ring) if r in d_from_stand]
    if not cands:
        return None
    walk, spawn = min(cands)
    if walk != plan["walk"]:
        return None

    ops = []
    targets = [("gunner", plan["g"], plan["facing"])]
    for tile, facing in plan["conveyors"]:
        targets.append(("conveyor", tile, facing))
    targets.append(("harvester", plan["ore"], None))

    cur = spawn
    built = set()
    for i, (kind, tile, facing) in enumerate(targets):
        seg = path_between(bd, cur, stands[i], blocker if i else frozenset())
        if seg is None:
            return None
        for s in seg:
            ops.append(("MOVE", s, 0, 0, ""))
        ops.append((kind.upper(), "", tile[0], tile[1], facing or ""))
        built.add(tile)
        cur = stands[i]
    return spawn, ops


TEMPLATE = '''"""GENERATED by tools/build_probe_rush.py -- executes one baked rush plan, verbatim.

One Builder Bot, one Gunner, one Harvester. The Core spawns exactly once and then idles, so nothing
perturbs the cost scale or the timeline. If the model in tools/build_rushplan_dual.py is right, the
match ends on the predicted turn with win_condition == 'core_destroyed'.
"""

from fcode import Controller, Direction, EntityType, Position

DIRS = {
    "NORTH": Direction.NORTH, "EAST": Direction.EAST,
    "SOUTH": Direction.SOUTH, "WEST": Direction.WEST,
}

# (map_w, map_h, core_x, core_y) -> (spawn, ops)
PLAN = %(table)s


class Player:
    def __init__(self):
        self.plan = None
        self.spawned = False
        self.i = 0
        self.looked = False

    def _lookup(self, ct):
        if self.looked:
            return self.plan
        self.looked = True
        try:
            p = ct.get_position()
            self.plan = PLAN.get((ct.get_map_width(), ct.get_map_height(), p.x, p.y))
        except Exception:
            self.plan = None
        return self.plan

    def run(self, ct: Controller) -> None:
        try:
            et = ct.get_entity_type()
        except Exception:
            return
        try:
            if et == EntityType.CORE:
                self._core(ct)
            elif et == EntityType.BUILDER_BOT:
                self._builder(ct)
            elif et == EntityType.GUNNER:
                self._gunner(ct)
        except Exception:
            pass

    def _core(self, ct):
        if self.spawned:
            return
        p = self._lookup(ct)
        if p is None:
            return
        self.spawned = True
        ct.spawn_builder(Position(p[0][0], p[0][1]))

    def _builder(self, ct):
        if self.plan is None:
            # builders get their own Player instance; re-derive from the store-free constant table
            for key, val in PLAN.items():
                if key[0] == ct.get_map_width() and key[1] == ct.get_map_height():
                    pos = ct.get_position()
                    if abs(pos.x - key[2]) <= 3 and abs(pos.y - key[3]) <= 3:
                        self.plan = val
                        break
            if self.plan is None:
                return
        ops = self.plan[1]
        if self.i >= len(ops):
            return
        op, arg, x, y, facing = ops[self.i]
        try:
            if op == "MOVE":
                ct.move(DIRS[arg])
            elif op == "GUNNER":
                ct.build_gunner(Position(x, y), DIRS[facing])
            elif op == "CONVEYOR":
                ct.build_conveyor(Position(x, y), DIRS[facing])
            elif op == "HARVESTER":
                ct.build_harvester(Position(x, y))
        except Exception:
            return
        self.i += 1

    def _gunner(self, ct):
        try:
            t = ct.get_gunner_target()
        except Exception:
            return
        if t is None:
            return
        try:
            if ct.can_fire(t):
                ct.fire(t)
        except Exception:
            return
'''


def main():
    rows = analyse()
    table = {}
    predicted = {}
    for (name, team), r in rows.items():
        p = r["plan"]
        if p is None:
            continue
        bd = r["bd"]
        got = build_steps(bd, p)
        if got is None:
            print("!! no executable route for %s/%s" % (name, team))
            continue
        spawn, ops = got
        key = (bd.w, bd.h, bd.team_own_core[0], bd.team_own_core[1])
        table[key] = (spawn, tuple(ops))
        predicted[(name, team)] = p["turns"]

    body = "{\n"
    for k in sorted(table):
        spawn, ops = table[k]
        o = ", ".join('("%s", "%s", %d, %d, "%s")' % op for op in ops)
        body += "    %r: (%r, (%s)),\n" % (k, spawn, o)
    body += "}"

    out = ROOT / "bots" / "probe_rush"
    out.mkdir(parents=True, exist_ok=True)
    (out / "main.py").write_text(TEMPLATE % {"table": body}, encoding="utf-8", newline="\n")
    (ROOT / "tools" / "_predicted.py").write_text(
        "PREDICTED = %r\n" % ({("%s" % k[0], k[1]): v for k, v in predicted.items()}),
        encoding="utf-8", newline="\n")
    print("wrote %s (%d map/team routes)" % (out / "main.py", len(table)))


if __name__ == "__main__":
    main()
