"""Generate `ragnarok_fair` from `ragnarok` by removing the offline atlas.

The two bots must never drift, so the fair one is generated rather than
maintained. The atlas is a genuine information advantage -- static terrain and
the enemy Core before either is scouted -- and `tournament/fairness.py` flags a
bot as unfair on the *import* alone, so making `identify_visible` return None
would not be enough: the import itself has to go, along with the modules.

Every atlas-conditional branch in ragnarok already has an observation-only
arm (that is the path it takes on an unrecognised map), so this only ever
pins those branches to the arm the fair bot would take anyway.

    uv run python tools/build_ragnarok_fair.py
"""

from __future__ import annotations

import shutil
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
SOURCE = REPO / "bots/luc/ragnarok"
DEST = REPO / "bots/luc/ragnarok_fair"

DROP_FILES = ("atlas.py", "atlas_data.py")

# (file, old, new) -- every replacement must match exactly once.
EDITS = (
    ("builder.py", "from atlas import identify_visible\n", ""),
    (
        "builder.py",
        "        p.atlas = (identify_visible(ct, own_core) if own_core is not None\n"
        "                   else None)\n",
        "        # No atlas: terrain and the enemy Core come only from what this\n"
        "        # Builder has seen and from the symmetry inference below.\n"
        "        p.atlas = None\n",
    ),
    ("core.py", "from atlas import identify_visible\n", ""),
    (
        "core.py",
        "        player.atlas = identify_visible(ct, tuple(core))\n",
        "        player.atlas = None\n",
    ),
    (
        "main.py",
        '"""Ragnarok:',
        '"""Ragnarok Fair (generated by build_ragnarok_fair.py -- do not edit):',
    ),
    (
        "BOT_VERSION.toml",
        'source_path = "bots/luc/ragnarok"',
        'source_path = "bots/luc/ragnarok_fair"',
    ),
    (
        "README.md",
        "# Ragnarok\n",
        "# Ragnarok Fair\n\n**Generated** from `bots/luc/ragnarok` by\n"
        "`tools/build_ragnarok_fair.py` with the offline map atlas removed.\n"
        "Do not edit these files; edit ragnarok and regenerate.\n",
    ),
)


def main() -> int:
    if DEST.exists():
        shutil.rmtree(DEST)
    DEST.mkdir(parents=True)

    for path in sorted(SOURCE.rglob("*")):
        if not path.is_file() or "__pycache__" in path.parts:
            continue
        name = path.relative_to(SOURCE)
        if str(name) in DROP_FILES:
            continue
        (DEST / name).parent.mkdir(parents=True, exist_ok=True)
        (DEST / name).write_bytes(path.read_bytes())

    for filename, old, new in EDITS:
        target = DEST / filename
        source = target.read_text()
        if source.count(old) != 1:
            print(f"{filename}: expected exactly one occurrence of\n{old!r}\n"
                  f"found {source.count(old)}", file=sys.stderr)
            return 1
        target.write_text(source.replace(old, new, 1))

    # The whole point: no module may mention the atlas at all.
    for path in DEST.rglob("*.py"):
        for number, line in enumerate(path.read_text().splitlines(), start=1):
            stripped = line.strip()
            if stripped.startswith(("import atlas", "from atlas")):
                print(f"{path}:{number}: atlas import survived", file=sys.stderr)
                return 1

    print(f"generated {DEST.relative_to(REPO)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
