"""Extract the competition pool's terrain into a table a bot can carry.

A bot sees only its own vision, but a *replay* carries the whole map, so one
throwaway match per map yields its exact terrain. The result is written as
`mapdata.py`, which `atlas.py` matches the live board against.

This is deliberately an "unfair" capability in this repo's sense: it works
because the ladder draws from a published pool, and it will not work in a
final played on unseen maps. It lives behind `bots/jon/unfair/` for that
reason. What it buys is knowledge of every deposit and the symmetry axis on
round 0, which is the single largest measured weakness of the fair bot --
first Harvester on round 14 against the top ten's 3 to 6, because Builders
spend ten rounds finding ore that a known map would hand them immediately.

    uv run python tools/build_mapdata.py
"""

from __future__ import annotations

import subprocess
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))

from analyze_mining_lanes import initial_state  # noqa: E402
from sweep import POOL, ROOT  # noqa: E402

# Environment ordering in fcode: EMPTY, WALL, ORE_TITANIUM.
EMPTY, WALL, ORE = 0, 1, 2
SYMMETRIES = ("MIRROR_X", "MIRROR_Y", "ROT_180")
OUT = ROOT / "bots" / "jon" / "unfair" / "brokkr_atlas" / "mapdata.py"


def grid_for(map_name: str):
    """Full terrain of one pool map, via a one-round throwaway replay."""
    replay = Path(f"/tmp/mapdata_{map_name}.replay26")
    subprocess.run(
        ["uv", "run", "fcode", "run", "bots/common/donothingbot",
         "bots/common/donothingbot", map_name, "--seed", "1", "--json",
         "--mark", "0", "--tle", "0", "--replay", str(replay)],
        cwd=ROOT, capture_output=True, text=True, timeout=600, check=True)
    width, height, grid, _entities = initial_state(replay.read_bytes())
    return width, height, grid


def symmetry_of(width: int, height: int, grid) -> str | None:
    """Which of the three symmetries the terrain actually satisfies."""
    def at(x, y):
        return grid[y][x]
    for kind in SYMMETRIES:
        ok = True
        for y in range(height):
            for x in range(width):
                if kind == "MIRROR_X":
                    mx, my = width - 1 - x, y
                elif kind == "MIRROR_Y":
                    mx, my = x, height - 1 - y
                else:
                    mx, my = width - 1 - x, height - 1 - y
                if at(x, y) != at(mx, my):
                    ok = False
                    break
            if not ok:
                break
        if ok:
            return kind
    return None


def main() -> None:
    rows = []
    for name in POOL:
        width, height, grid = grid_for(name)
        kind = symmetry_of(width, height, grid)
        # One string per row, one character per tile. 15 maps of at most 900
        # tiles is about 13 KB of source -- small enough to carry, and exact,
        # which a hash would not be: identification has to work from partial
        # vision, so the whole grid has to be comparable tile by tile.
        packed = ["".join(str(v) for v in row) for row in grid]
        ore = sorted((x, y) for y, row in enumerate(grid)
                     for x, v in enumerate(row) if v == ORE)
        rows.append((name, width, height, kind, packed, ore))
        print(f"{name:<14} {width}x{height:<3} symmetry={kind} ore={len(ore)}")

    body = ['"""Terrain of the competition map pool, generated by',
            'tools/build_mapdata.py. Do not edit by hand.',
            '',
            'Each entry is (width, height, symmetry, rows, ore). `rows` is one',
            'string per map row, one character per tile: 0 empty, 1 wall, 2 ore.',
            '"""',
            '',
            'SYMMETRIES = ("MIRROR_X", "MIRROR_Y", "ROT_180")',
            '',
            'MAPS = {']
    for name, width, height, kind, packed, ore in rows:
        body.append(f'    "{name}": (')
        body.append(f'        {width}, {height}, {kind!r},')
        body.append('        (')
        for row in packed:
            body.append(f'            "{row}",')
        body.append('        ),')
        body.append(f'        {tuple(ore)!r},')
        body.append('    ),')
    body.append('}')
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text("\n".join(body) + "\n")
    print(f"\nwrote {OUT} ({OUT.stat().st_size} bytes)")


if __name__ == "__main__":
    main()
