"""Regenerate bots/elias/rush/terrain.py from the current map pool.

The rusher plans a true shortest path from round 0 by knowing the pool's walls up front. That table
goes stale the moment an admin rotates the pool -- which is exactly what killed `bots/nash/flagship/
atlas.py`, a hardcoded oracle keyed on 21 maps that are all retired, so it returns None on every
live map and has been dead weight ever since.

Run this after `fcode maps sync` whenever the pool changes:

    python tools/gen_terrain.py

Unknown maps are not a failure: the bot falls back to observing terrain and mirroring it across the
map's symmetry, so a stale table costs speed, never correctness.
"""

import pathlib
import sys

sys.path.insert(0, str(pathlib.Path(__file__).resolve().parent))
import mapio

ROOT = pathlib.Path(__file__).resolve().parent.parent
OUT = ROOT / "bots" / "elias" / "rush" / "terrain.py"


def symmetry(width, height, grid, cores):
    """Which reflection maps the terrain onto itself: 'R', 'H' or 'V'.

    Measured over the whole pool, terrain is EXACTLY symmetric -- zero mismatched tiles -- so this
    is a decision, not a best fit. Note the offset: terrain reflects about W-1 while the Core pair
    reflects about W-2, because the Core is 2x2 and is named by its north-west corner.
    """
    def holds(kind):
        for y in range(height):
            for x in range(width):
                if kind == "H":
                    tx, ty = width - 1 - x, y
                elif kind == "V":
                    tx, ty = x, height - 1 - y
                else:
                    tx, ty = width - 1 - x, height - 1 - y
                if grid[ty][tx] != grid[y][x]:
                    return False
        return True

    first, second = cores
    for kind in ("H", "V", "R"):
        if kind == "H":
            guess = (width - 2 - first[0], first[1])
        elif kind == "V":
            guess = (first[0], height - 2 - first[1])
        else:
            guess = (width - 2 - first[0], height - 2 - first[1])
        if guess == second and holds(kind):
            return kind
    return None


def load(path):
    width, height, rows, cores = mapio.dump(str(path))
    cells = []
    for row in rows:
        cells.extend(list(row) if isinstance(row, (bytes, bytearray)) else [row])
    grid = [cells[y * width:(y + 1) * width] for y in range(height)]
    spots = [(c.get("pos", {}).get(1, 0), c.get("pos", {}).get(2, 0)) for c in cores]
    return width, height, grid, cells, spots


def main():
    index, walls, skipped = {}, {}, []
    for path in sorted((ROOT / "maps").glob("*.map26")):
        width, height, grid, cells, cores = load(path)
        if len(cores) != 2:
            skipped.append((path.stem, "expected 2 Cores, found %d" % len(cores)))
            continue
        kind = symmetry(width, height, grid, cores)
        if kind is None:
            skipped.append((path.stem, "no reflection maps the Cores onto each other"))
            continue
        walls[path.stem] = (width, height,
                            "".join("1" if c == 1 else "2" if c == 2 else "0" for c in cells))
        for core in cores:
            index[(width, height, core[0], core[1])] = (kind, path.stem)

    out = ['"""Wall layout of the competition map pool, keyed by dimensions plus our own Core.',
           "",
           "GENERATED by tools/gen_terrain.py -- do not edit by hand. Regenerate after any pool",
           "rotation. A map absent from this table is not a failure: the bot falls back to observing",
           "terrain and mirroring it across the map's symmetry.",
           '"""',
           "",
           "# (width, height, own_core_x, own_core_y) -> (symmetry, map name)",
           "INDEX = {"]
    for key, value in sorted(index.items()):
        out.append("    %s: %r," % (key, value))
    out.append("}")
    out.append("")
    out.append("# name -> (width, height, row-major terrain map: '1' = WALL, '2' = ORE, '0' = empty)")
    out.append("WALLS = {")
    for name, (width, height, bits) in sorted(walls.items()):
        out.append("    %r: (%d, %d," % (name, width, height))
        for y in range(height):
            out.append("        %r" % bits[y * width:(y + 1) * width])
        out.append("    ),")
    out.append("}")
    OUT.write_text("\n".join(out) + "\n", encoding="utf-8")

    print("wrote %s" % OUT.relative_to(ROOT))
    print("  %d maps, %d seat keys" % (len(walls), len(index)))
    for name, why in skipped:
        print("  SKIPPED %-14s %s" % (name, why))


if __name__ == "__main__":
    main()
