"""Regenerate the static map atlas from maps/*.map26.

The .map26 files are protobuf. We only need three fields and the wire format
for them is stable enough to read directly, which avoids depending on a
generated stub that the engine does not ship:

    field 1, varint   width
    field 2, varint   height
    field 3, repeated {field 1, repeated int32}   one row, top row first
    field 4, repeated {field 1 team, field 3 {field 1 x, field 2 y}}  cores

Rows come in both protobuf encodings of a repeated scalar and the pool
contains each: the small maps pack the row into one length-delimited blob,
the large ones emit a separate varint per tile.  `_row` accepts either.

Tile codes are 0 empty, 1 wall, 2 ore -- confirmed by diffing the decoded
rows against the terrain the old hand-built atlas carried for the maps that
survive in the current pool.
"""

import pathlib
import sys

EMPTY, WALL, ORE = 0, 1, 2
GLYPH = {EMPTY: ".", WALL: "#", ORE: "O"}


def _varint(buf, i):
    value = shift = 0
    while True:
        byte = buf[i]
        i += 1
        value |= (byte & 0x7F) << shift
        if not byte & 0x80:
            return value, i
        shift += 7


def _fields(buf):
    """Yield (field_number, payload) for one protobuf message."""
    i = 0
    while i < len(buf):
        key, i = _varint(buf, i)
        number, wire = key >> 3, key & 7
        if wire == 0:
            value, i = _varint(buf, i)
            yield number, value
        elif wire == 2:
            length, i = _varint(buf, i)
            yield number, buf[i:i + length]
            i += length
        else:
            raise ValueError(f"unsupported wire type {wire}")


def _row(payload):
    """One row of tile codes, from either encoding of `repeated int32`."""
    tiles = []
    for number, value in _fields(payload):
        if number != 1:
            continue
        if isinstance(value, int):
            tiles.append(value)
        else:
            i = 0
            while i < len(value):
                tile, i = _varint(value, i)
                tiles.append(tile)
    return tiles


def parse(path):
    buf = path.read_bytes()
    width = height = None
    rows, cores = [], {}
    for number, payload in _fields(buf):
        if number == 1:
            width = payload
        elif number == 2:
            height = payload
        elif number == 3:
            rows.append(_row(payload))
        elif number == 4:
            team = spot = None
            for inner_number, inner in _fields(payload):
                if inner_number == 1:
                    team = inner
                elif inner_number == 3:
                    x = y = 0
                    for leaf_number, leaf in _fields(inner):
                        if leaf_number == 1:
                            x = leaf
                        elif leaf_number == 2:
                            y = leaf
                    spot = (x, y)
            cores[team] = spot
    if width is None or height is None or len(rows) != height:
        raise ValueError(f"{path.name}: expected {height} rows, got {len(rows)}")
    for row in rows:
        if len(row) != width:
            raise ValueError(f"{path.name}: row width {len(row)} != {width}")
    return width, height, rows, cores


def glyphs(rows):
    return tuple("".join(GLYPH[t] for t in row) for row in rows)


def main():
    root = pathlib.Path(sys.argv[1] if len(sys.argv) > 1 else ".")
    maps = sorted((root / "maps").glob("*.map26"))
    if not maps:
        sys.exit(f"no maps under {root / 'maps'}")

    entries, index = {}, {}
    for path in maps:
        name = path.stem
        width, height, rows, cores = parse(path)
        seats = [cores[team] for team in sorted(cores)]
        if len(seats) != 2:
            print(f"skip {name}: {len(seats)} cores", file=sys.stderr)
            continue
        entries[name] = (width, height, glyphs(rows), tuple(seats))
        for mine, theirs in (seats, seats[::-1]):
            index.setdefault((width, height, mine), []).append((name, theirs))

    out = [
        '"""Generated by tools/gen_atlas.py -- do not edit by hand."""\n',
        "# name -> (width, height, rows, (core_a, core_b))",
        "MAPS = {",
    ]
    for name, (width, height, rows, seats) in sorted(entries.items()):
        out.append(f"    {name!r}: ({width}, {height}, (")
        out.extend(f"        {row!r}," for row in rows)
        out.append(f"    ), {seats!r}),")
    out.append("}\n")
    out.append("# (width, height, our core anchor) -> [(name, their core anchor)]")
    out.append("# Five key collisions survive in the current pool -- maps that share")
    out.append("# dimensions and seating and differ only in terrain -- so the value is a")
    out.append("# list and atlas.identify settles it against what the Core can see.")
    out.append("INDEX = {")
    for key, value in sorted(index.items()):
        out.append(f"    {key!r}: {value!r},")
    out.append("}")
    ambiguous = sum(1 for v in index.values() if len(v) > 1)
    print(f"{ambiguous} ambiguous keys", file=sys.stderr)

    target = pathlib.Path(sys.argv[2]) if len(sys.argv) > 2 else (
        root / "bots" / "jon" / "brokkr" / "atlas_data.py")
    target.write_text("\n".join(out) + "\n")
    print(f"{len(entries)} maps -> {target} ({target.stat().st_size} bytes)")


if __name__ == "__main__":
    main()
